// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table implementation internals

#include "Vtop__pch.h"
#include "Vtop.h"
#include "Vtop___024root.h"

// FUNCTIONS
Vtop__Syms::~Vtop__Syms()
{

    // Tear down scope hierarchy
    __Vhier.remove(0, &__Vscope_cla);
    __Vhier.remove(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__0__KET____gp_inst);
    __Vhier.remove(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__10__KET____gp_inst);
    __Vhier.remove(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__11__KET____gp_inst);
    __Vhier.remove(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__12__KET____gp_inst);
    __Vhier.remove(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__13__KET____gp_inst);
    __Vhier.remove(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__14__KET____gp_inst);
    __Vhier.remove(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__15__KET____gp_inst);
    __Vhier.remove(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__16__KET____gp_inst);
    __Vhier.remove(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__17__KET____gp_inst);
    __Vhier.remove(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__18__KET____gp_inst);
    __Vhier.remove(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__19__KET____gp_inst);
    __Vhier.remove(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__1__KET____gp_inst);
    __Vhier.remove(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__20__KET____gp_inst);
    __Vhier.remove(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__21__KET____gp_inst);
    __Vhier.remove(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__22__KET____gp_inst);
    __Vhier.remove(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__23__KET____gp_inst);
    __Vhier.remove(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__24__KET____gp_inst);
    __Vhier.remove(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__25__KET____gp_inst);
    __Vhier.remove(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__26__KET____gp_inst);
    __Vhier.remove(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__27__KET____gp_inst);
    __Vhier.remove(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__28__KET____gp_inst);
    __Vhier.remove(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__29__KET____gp_inst);
    __Vhier.remove(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__2__KET____gp_inst);
    __Vhier.remove(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__30__KET____gp_inst);
    __Vhier.remove(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__31__KET____gp_inst);
    __Vhier.remove(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__3__KET____gp_inst);
    __Vhier.remove(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__4__KET____gp_inst);
    __Vhier.remove(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__5__KET____gp_inst);
    __Vhier.remove(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__6__KET____gp_inst);
    __Vhier.remove(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__7__KET____gp_inst);
    __Vhier.remove(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__8__KET____gp_inst);
    __Vhier.remove(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__9__KET____gp_inst);
    __Vhier.remove(&__Vscope_cla, &__Vscope_cla__gp8_high);
    __Vhier.remove(&__Vscope_cla, &__Vscope_cla__gp8_low);
    __Vhier.remove(&__Vscope_cla, &__Vscope_cla__gp8_mid1);
    __Vhier.remove(&__Vscope_cla, &__Vscope_cla__gp8_mid2);
    __Vhier.remove(&__Vscope_cla__gp8_high, &__Vscope_cla__gp8_high__gp_segment_high);
    __Vhier.remove(&__Vscope_cla__gp8_high, &__Vscope_cla__gp8_high__gp_segment_low);
    __Vhier.remove(&__Vscope_cla__gp8_low, &__Vscope_cla__gp8_low__gp_segment_high);
    __Vhier.remove(&__Vscope_cla__gp8_low, &__Vscope_cla__gp8_low__gp_segment_low);
    __Vhier.remove(&__Vscope_cla__gp8_mid1, &__Vscope_cla__gp8_mid1__gp_segment_high);
    __Vhier.remove(&__Vscope_cla__gp8_mid1, &__Vscope_cla__gp8_mid1__gp_segment_low);
    __Vhier.remove(&__Vscope_cla__gp8_mid2, &__Vscope_cla__gp8_mid2__gp_segment_high);
    __Vhier.remove(&__Vscope_cla__gp8_mid2, &__Vscope_cla__gp8_mid2__gp_segment_low);

}

Vtop__Syms::Vtop__Syms(VerilatedContext* contextp, const char* namep, Vtop* modelp)
    : VerilatedSyms{contextp}
    // Setup internal state of the Syms class
    , __Vm_modelp{modelp}
    // Setup module instances
    , TOP{this, namep}
{
        // Check resources
        Verilated::stackCheck(241);
    // Configure time unit / time precision
    _vm_contextp__->timeunit(-9);
    _vm_contextp__->timeprecision(-12);
    // Setup each module's pointers to their submodules
    // Setup each module's pointer back to symbol table (for public functions)
    TOP.__Vconfigure(true);
    // Setup scopes
    __Vscope_TOP.configure(this, name(), "TOP", "TOP", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_cla.configure(this, name(), "cla", "cla", "cla", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_cla__gp1_loop__BRA__0__KET____gp_inst.configure(this, name(), "cla.gp1_loop[0].gp_inst", "gp_inst", "gp1", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_cla__gp1_loop__BRA__10__KET____gp_inst.configure(this, name(), "cla.gp1_loop[10].gp_inst", "gp_inst", "gp1", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_cla__gp1_loop__BRA__11__KET____gp_inst.configure(this, name(), "cla.gp1_loop[11].gp_inst", "gp_inst", "gp1", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_cla__gp1_loop__BRA__12__KET____gp_inst.configure(this, name(), "cla.gp1_loop[12].gp_inst", "gp_inst", "gp1", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_cla__gp1_loop__BRA__13__KET____gp_inst.configure(this, name(), "cla.gp1_loop[13].gp_inst", "gp_inst", "gp1", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_cla__gp1_loop__BRA__14__KET____gp_inst.configure(this, name(), "cla.gp1_loop[14].gp_inst", "gp_inst", "gp1", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_cla__gp1_loop__BRA__15__KET____gp_inst.configure(this, name(), "cla.gp1_loop[15].gp_inst", "gp_inst", "gp1", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_cla__gp1_loop__BRA__16__KET____gp_inst.configure(this, name(), "cla.gp1_loop[16].gp_inst", "gp_inst", "gp1", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_cla__gp1_loop__BRA__17__KET____gp_inst.configure(this, name(), "cla.gp1_loop[17].gp_inst", "gp_inst", "gp1", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_cla__gp1_loop__BRA__18__KET____gp_inst.configure(this, name(), "cla.gp1_loop[18].gp_inst", "gp_inst", "gp1", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_cla__gp1_loop__BRA__19__KET____gp_inst.configure(this, name(), "cla.gp1_loop[19].gp_inst", "gp_inst", "gp1", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_cla__gp1_loop__BRA__1__KET____gp_inst.configure(this, name(), "cla.gp1_loop[1].gp_inst", "gp_inst", "gp1", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_cla__gp1_loop__BRA__20__KET____gp_inst.configure(this, name(), "cla.gp1_loop[20].gp_inst", "gp_inst", "gp1", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_cla__gp1_loop__BRA__21__KET____gp_inst.configure(this, name(), "cla.gp1_loop[21].gp_inst", "gp_inst", "gp1", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_cla__gp1_loop__BRA__22__KET____gp_inst.configure(this, name(), "cla.gp1_loop[22].gp_inst", "gp_inst", "gp1", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_cla__gp1_loop__BRA__23__KET____gp_inst.configure(this, name(), "cla.gp1_loop[23].gp_inst", "gp_inst", "gp1", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_cla__gp1_loop__BRA__24__KET____gp_inst.configure(this, name(), "cla.gp1_loop[24].gp_inst", "gp_inst", "gp1", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_cla__gp1_loop__BRA__25__KET____gp_inst.configure(this, name(), "cla.gp1_loop[25].gp_inst", "gp_inst", "gp1", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_cla__gp1_loop__BRA__26__KET____gp_inst.configure(this, name(), "cla.gp1_loop[26].gp_inst", "gp_inst", "gp1", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_cla__gp1_loop__BRA__27__KET____gp_inst.configure(this, name(), "cla.gp1_loop[27].gp_inst", "gp_inst", "gp1", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_cla__gp1_loop__BRA__28__KET____gp_inst.configure(this, name(), "cla.gp1_loop[28].gp_inst", "gp_inst", "gp1", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_cla__gp1_loop__BRA__29__KET____gp_inst.configure(this, name(), "cla.gp1_loop[29].gp_inst", "gp_inst", "gp1", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_cla__gp1_loop__BRA__2__KET____gp_inst.configure(this, name(), "cla.gp1_loop[2].gp_inst", "gp_inst", "gp1", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_cla__gp1_loop__BRA__30__KET____gp_inst.configure(this, name(), "cla.gp1_loop[30].gp_inst", "gp_inst", "gp1", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_cla__gp1_loop__BRA__31__KET____gp_inst.configure(this, name(), "cla.gp1_loop[31].gp_inst", "gp_inst", "gp1", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_cla__gp1_loop__BRA__3__KET____gp_inst.configure(this, name(), "cla.gp1_loop[3].gp_inst", "gp_inst", "gp1", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_cla__gp1_loop__BRA__4__KET____gp_inst.configure(this, name(), "cla.gp1_loop[4].gp_inst", "gp_inst", "gp1", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_cla__gp1_loop__BRA__5__KET____gp_inst.configure(this, name(), "cla.gp1_loop[5].gp_inst", "gp_inst", "gp1", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_cla__gp1_loop__BRA__6__KET____gp_inst.configure(this, name(), "cla.gp1_loop[6].gp_inst", "gp_inst", "gp1", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_cla__gp1_loop__BRA__7__KET____gp_inst.configure(this, name(), "cla.gp1_loop[7].gp_inst", "gp_inst", "gp1", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_cla__gp1_loop__BRA__8__KET____gp_inst.configure(this, name(), "cla.gp1_loop[8].gp_inst", "gp_inst", "gp1", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_cla__gp1_loop__BRA__9__KET____gp_inst.configure(this, name(), "cla.gp1_loop[9].gp_inst", "gp_inst", "gp1", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_cla__gp8_high.configure(this, name(), "cla.gp8_high", "gp8_high", "gp8", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_cla__gp8_high__gp_segment_high.configure(this, name(), "cla.gp8_high.gp_segment_high", "gp_segment_high", "gp4", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_cla__gp8_high__gp_segment_low.configure(this, name(), "cla.gp8_high.gp_segment_low", "gp_segment_low", "gp4", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_cla__gp8_low.configure(this, name(), "cla.gp8_low", "gp8_low", "gp8", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_cla__gp8_low__gp_segment_high.configure(this, name(), "cla.gp8_low.gp_segment_high", "gp_segment_high", "gp4", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_cla__gp8_low__gp_segment_low.configure(this, name(), "cla.gp8_low.gp_segment_low", "gp_segment_low", "gp4", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_cla__gp8_mid1.configure(this, name(), "cla.gp8_mid1", "gp8_mid1", "gp8", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_cla__gp8_mid1__gp_segment_high.configure(this, name(), "cla.gp8_mid1.gp_segment_high", "gp_segment_high", "gp4", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_cla__gp8_mid1__gp_segment_low.configure(this, name(), "cla.gp8_mid1.gp_segment_low", "gp_segment_low", "gp4", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_cla__gp8_mid2.configure(this, name(), "cla.gp8_mid2", "gp8_mid2", "gp8", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_cla__gp8_mid2__gp_segment_high.configure(this, name(), "cla.gp8_mid2.gp_segment_high", "gp_segment_high", "gp4", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_cla__gp8_mid2__gp_segment_low.configure(this, name(), "cla.gp8_mid2.gp_segment_low", "gp_segment_low", "gp4", -9, VerilatedScope::SCOPE_MODULE);

    // Set up scope hierarchy
    __Vhier.add(0, &__Vscope_cla);
    __Vhier.add(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__0__KET____gp_inst);
    __Vhier.add(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__10__KET____gp_inst);
    __Vhier.add(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__11__KET____gp_inst);
    __Vhier.add(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__12__KET____gp_inst);
    __Vhier.add(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__13__KET____gp_inst);
    __Vhier.add(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__14__KET____gp_inst);
    __Vhier.add(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__15__KET____gp_inst);
    __Vhier.add(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__16__KET____gp_inst);
    __Vhier.add(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__17__KET____gp_inst);
    __Vhier.add(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__18__KET____gp_inst);
    __Vhier.add(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__19__KET____gp_inst);
    __Vhier.add(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__1__KET____gp_inst);
    __Vhier.add(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__20__KET____gp_inst);
    __Vhier.add(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__21__KET____gp_inst);
    __Vhier.add(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__22__KET____gp_inst);
    __Vhier.add(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__23__KET____gp_inst);
    __Vhier.add(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__24__KET____gp_inst);
    __Vhier.add(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__25__KET____gp_inst);
    __Vhier.add(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__26__KET____gp_inst);
    __Vhier.add(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__27__KET____gp_inst);
    __Vhier.add(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__28__KET____gp_inst);
    __Vhier.add(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__29__KET____gp_inst);
    __Vhier.add(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__2__KET____gp_inst);
    __Vhier.add(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__30__KET____gp_inst);
    __Vhier.add(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__31__KET____gp_inst);
    __Vhier.add(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__3__KET____gp_inst);
    __Vhier.add(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__4__KET____gp_inst);
    __Vhier.add(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__5__KET____gp_inst);
    __Vhier.add(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__6__KET____gp_inst);
    __Vhier.add(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__7__KET____gp_inst);
    __Vhier.add(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__8__KET____gp_inst);
    __Vhier.add(&__Vscope_cla, &__Vscope_cla__gp1_loop__BRA__9__KET____gp_inst);
    __Vhier.add(&__Vscope_cla, &__Vscope_cla__gp8_high);
    __Vhier.add(&__Vscope_cla, &__Vscope_cla__gp8_low);
    __Vhier.add(&__Vscope_cla, &__Vscope_cla__gp8_mid1);
    __Vhier.add(&__Vscope_cla, &__Vscope_cla__gp8_mid2);
    __Vhier.add(&__Vscope_cla__gp8_high, &__Vscope_cla__gp8_high__gp_segment_high);
    __Vhier.add(&__Vscope_cla__gp8_high, &__Vscope_cla__gp8_high__gp_segment_low);
    __Vhier.add(&__Vscope_cla__gp8_low, &__Vscope_cla__gp8_low__gp_segment_high);
    __Vhier.add(&__Vscope_cla__gp8_low, &__Vscope_cla__gp8_low__gp_segment_low);
    __Vhier.add(&__Vscope_cla__gp8_mid1, &__Vscope_cla__gp8_mid1__gp_segment_high);
    __Vhier.add(&__Vscope_cla__gp8_mid1, &__Vscope_cla__gp8_mid1__gp_segment_low);
    __Vhier.add(&__Vscope_cla__gp8_mid2, &__Vscope_cla__gp8_mid2__gp_segment_high);
    __Vhier.add(&__Vscope_cla__gp8_mid2, &__Vscope_cla__gp8_mid2__gp_segment_low);

    // Setup export functions
    for (int __Vfinal = 0; __Vfinal < 2; ++__Vfinal) {
        __Vscope_TOP.varInsert(__Vfinal,"a", &(TOP.a), false, VLVT_UINT32,VLVD_IN|VLVF_PUB_RW,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"b", &(TOP.b), false, VLVT_UINT32,VLVD_IN|VLVF_PUB_RW,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"cin", &(TOP.cin), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"sum", &(TOP.sum), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,1 ,31,0);
        __Vscope_cla.varInsert(__Vfinal,"a", &(TOP.cla__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_cla.varInsert(__Vfinal,"b", &(TOP.cla__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_cla.varInsert(__Vfinal,"c16", &(TOP.cla__DOT__c16), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla.varInsert(__Vfinal,"c24", &(TOP.cla__DOT__c24), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla.varInsert(__Vfinal,"c8", &(TOP.cla__DOT__c8), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla.varInsert(__Vfinal,"carry", &(TOP.cla__DOT__carry), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_cla.varInsert(__Vfinal,"cin", &(TOP.cla__DOT__cin), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla.varInsert(__Vfinal,"g", &(TOP.cla__DOT__g), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_cla.varInsert(__Vfinal,"gout", &(TOP.cla__DOT__gout), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_cla.varInsert(__Vfinal,"p", &(TOP.cla__DOT__p), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_cla.varInsert(__Vfinal,"pout", &(TOP.cla__DOT__pout), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_cla.varInsert(__Vfinal,"sum", &(TOP.cla__DOT__sum), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_cla__gp1_loop__BRA__0__KET____gp_inst.varInsert(__Vfinal,"a", &(TOP.cla__DOT__gp1_loop__BRA__0__KET____DOT__gp_inst__DOT__a), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__0__KET____gp_inst.varInsert(__Vfinal,"b", &(TOP.cla__DOT__gp1_loop__BRA__0__KET____DOT__gp_inst__DOT__b), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__0__KET____gp_inst.varInsert(__Vfinal,"g", &(TOP.cla__DOT__gp1_loop__BRA__0__KET____DOT__gp_inst__DOT__g), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__0__KET____gp_inst.varInsert(__Vfinal,"p", &(TOP.cla__DOT__gp1_loop__BRA__0__KET____DOT__gp_inst__DOT__p), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__10__KET____gp_inst.varInsert(__Vfinal,"a", &(TOP.cla__DOT__gp1_loop__BRA__10__KET____DOT__gp_inst__DOT__a), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__10__KET____gp_inst.varInsert(__Vfinal,"b", &(TOP.cla__DOT__gp1_loop__BRA__10__KET____DOT__gp_inst__DOT__b), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__10__KET____gp_inst.varInsert(__Vfinal,"g", &(TOP.cla__DOT__gp1_loop__BRA__10__KET____DOT__gp_inst__DOT__g), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__10__KET____gp_inst.varInsert(__Vfinal,"p", &(TOP.cla__DOT__gp1_loop__BRA__10__KET____DOT__gp_inst__DOT__p), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__11__KET____gp_inst.varInsert(__Vfinal,"a", &(TOP.cla__DOT__gp1_loop__BRA__11__KET____DOT__gp_inst__DOT__a), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__11__KET____gp_inst.varInsert(__Vfinal,"b", &(TOP.cla__DOT__gp1_loop__BRA__11__KET____DOT__gp_inst__DOT__b), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__11__KET____gp_inst.varInsert(__Vfinal,"g", &(TOP.cla__DOT__gp1_loop__BRA__11__KET____DOT__gp_inst__DOT__g), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__11__KET____gp_inst.varInsert(__Vfinal,"p", &(TOP.cla__DOT__gp1_loop__BRA__11__KET____DOT__gp_inst__DOT__p), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__12__KET____gp_inst.varInsert(__Vfinal,"a", &(TOP.cla__DOT__gp1_loop__BRA__12__KET____DOT__gp_inst__DOT__a), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__12__KET____gp_inst.varInsert(__Vfinal,"b", &(TOP.cla__DOT__gp1_loop__BRA__12__KET____DOT__gp_inst__DOT__b), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__12__KET____gp_inst.varInsert(__Vfinal,"g", &(TOP.cla__DOT__gp1_loop__BRA__12__KET____DOT__gp_inst__DOT__g), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__12__KET____gp_inst.varInsert(__Vfinal,"p", &(TOP.cla__DOT__gp1_loop__BRA__12__KET____DOT__gp_inst__DOT__p), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__13__KET____gp_inst.varInsert(__Vfinal,"a", &(TOP.cla__DOT__gp1_loop__BRA__13__KET____DOT__gp_inst__DOT__a), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__13__KET____gp_inst.varInsert(__Vfinal,"b", &(TOP.cla__DOT__gp1_loop__BRA__13__KET____DOT__gp_inst__DOT__b), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__13__KET____gp_inst.varInsert(__Vfinal,"g", &(TOP.cla__DOT__gp1_loop__BRA__13__KET____DOT__gp_inst__DOT__g), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__13__KET____gp_inst.varInsert(__Vfinal,"p", &(TOP.cla__DOT__gp1_loop__BRA__13__KET____DOT__gp_inst__DOT__p), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__14__KET____gp_inst.varInsert(__Vfinal,"a", &(TOP.cla__DOT__gp1_loop__BRA__14__KET____DOT__gp_inst__DOT__a), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__14__KET____gp_inst.varInsert(__Vfinal,"b", &(TOP.cla__DOT__gp1_loop__BRA__14__KET____DOT__gp_inst__DOT__b), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__14__KET____gp_inst.varInsert(__Vfinal,"g", &(TOP.cla__DOT__gp1_loop__BRA__14__KET____DOT__gp_inst__DOT__g), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__14__KET____gp_inst.varInsert(__Vfinal,"p", &(TOP.cla__DOT__gp1_loop__BRA__14__KET____DOT__gp_inst__DOT__p), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__15__KET____gp_inst.varInsert(__Vfinal,"a", &(TOP.cla__DOT__gp1_loop__BRA__15__KET____DOT__gp_inst__DOT__a), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__15__KET____gp_inst.varInsert(__Vfinal,"b", &(TOP.cla__DOT__gp1_loop__BRA__15__KET____DOT__gp_inst__DOT__b), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__15__KET____gp_inst.varInsert(__Vfinal,"g", &(TOP.cla__DOT__gp1_loop__BRA__15__KET____DOT__gp_inst__DOT__g), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__15__KET____gp_inst.varInsert(__Vfinal,"p", &(TOP.cla__DOT__gp1_loop__BRA__15__KET____DOT__gp_inst__DOT__p), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__16__KET____gp_inst.varInsert(__Vfinal,"a", &(TOP.cla__DOT__gp1_loop__BRA__16__KET____DOT__gp_inst__DOT__a), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__16__KET____gp_inst.varInsert(__Vfinal,"b", &(TOP.cla__DOT__gp1_loop__BRA__16__KET____DOT__gp_inst__DOT__b), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__16__KET____gp_inst.varInsert(__Vfinal,"g", &(TOP.cla__DOT__gp1_loop__BRA__16__KET____DOT__gp_inst__DOT__g), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__16__KET____gp_inst.varInsert(__Vfinal,"p", &(TOP.cla__DOT__gp1_loop__BRA__16__KET____DOT__gp_inst__DOT__p), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__17__KET____gp_inst.varInsert(__Vfinal,"a", &(TOP.cla__DOT__gp1_loop__BRA__17__KET____DOT__gp_inst__DOT__a), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__17__KET____gp_inst.varInsert(__Vfinal,"b", &(TOP.cla__DOT__gp1_loop__BRA__17__KET____DOT__gp_inst__DOT__b), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__17__KET____gp_inst.varInsert(__Vfinal,"g", &(TOP.cla__DOT__gp1_loop__BRA__17__KET____DOT__gp_inst__DOT__g), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__17__KET____gp_inst.varInsert(__Vfinal,"p", &(TOP.cla__DOT__gp1_loop__BRA__17__KET____DOT__gp_inst__DOT__p), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__18__KET____gp_inst.varInsert(__Vfinal,"a", &(TOP.cla__DOT__gp1_loop__BRA__18__KET____DOT__gp_inst__DOT__a), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__18__KET____gp_inst.varInsert(__Vfinal,"b", &(TOP.cla__DOT__gp1_loop__BRA__18__KET____DOT__gp_inst__DOT__b), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__18__KET____gp_inst.varInsert(__Vfinal,"g", &(TOP.cla__DOT__gp1_loop__BRA__18__KET____DOT__gp_inst__DOT__g), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__18__KET____gp_inst.varInsert(__Vfinal,"p", &(TOP.cla__DOT__gp1_loop__BRA__18__KET____DOT__gp_inst__DOT__p), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__19__KET____gp_inst.varInsert(__Vfinal,"a", &(TOP.cla__DOT__gp1_loop__BRA__19__KET____DOT__gp_inst__DOT__a), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__19__KET____gp_inst.varInsert(__Vfinal,"b", &(TOP.cla__DOT__gp1_loop__BRA__19__KET____DOT__gp_inst__DOT__b), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__19__KET____gp_inst.varInsert(__Vfinal,"g", &(TOP.cla__DOT__gp1_loop__BRA__19__KET____DOT__gp_inst__DOT__g), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__19__KET____gp_inst.varInsert(__Vfinal,"p", &(TOP.cla__DOT__gp1_loop__BRA__19__KET____DOT__gp_inst__DOT__p), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__1__KET____gp_inst.varInsert(__Vfinal,"a", &(TOP.cla__DOT__gp1_loop__BRA__1__KET____DOT__gp_inst__DOT__a), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__1__KET____gp_inst.varInsert(__Vfinal,"b", &(TOP.cla__DOT__gp1_loop__BRA__1__KET____DOT__gp_inst__DOT__b), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__1__KET____gp_inst.varInsert(__Vfinal,"g", &(TOP.cla__DOT__gp1_loop__BRA__1__KET____DOT__gp_inst__DOT__g), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__1__KET____gp_inst.varInsert(__Vfinal,"p", &(TOP.cla__DOT__gp1_loop__BRA__1__KET____DOT__gp_inst__DOT__p), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__20__KET____gp_inst.varInsert(__Vfinal,"a", &(TOP.cla__DOT__gp1_loop__BRA__20__KET____DOT__gp_inst__DOT__a), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__20__KET____gp_inst.varInsert(__Vfinal,"b", &(TOP.cla__DOT__gp1_loop__BRA__20__KET____DOT__gp_inst__DOT__b), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__20__KET____gp_inst.varInsert(__Vfinal,"g", &(TOP.cla__DOT__gp1_loop__BRA__20__KET____DOT__gp_inst__DOT__g), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__20__KET____gp_inst.varInsert(__Vfinal,"p", &(TOP.cla__DOT__gp1_loop__BRA__20__KET____DOT__gp_inst__DOT__p), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__21__KET____gp_inst.varInsert(__Vfinal,"a", &(TOP.cla__DOT__gp1_loop__BRA__21__KET____DOT__gp_inst__DOT__a), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__21__KET____gp_inst.varInsert(__Vfinal,"b", &(TOP.cla__DOT__gp1_loop__BRA__21__KET____DOT__gp_inst__DOT__b), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__21__KET____gp_inst.varInsert(__Vfinal,"g", &(TOP.cla__DOT__gp1_loop__BRA__21__KET____DOT__gp_inst__DOT__g), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__21__KET____gp_inst.varInsert(__Vfinal,"p", &(TOP.cla__DOT__gp1_loop__BRA__21__KET____DOT__gp_inst__DOT__p), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__22__KET____gp_inst.varInsert(__Vfinal,"a", &(TOP.cla__DOT__gp1_loop__BRA__22__KET____DOT__gp_inst__DOT__a), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__22__KET____gp_inst.varInsert(__Vfinal,"b", &(TOP.cla__DOT__gp1_loop__BRA__22__KET____DOT__gp_inst__DOT__b), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__22__KET____gp_inst.varInsert(__Vfinal,"g", &(TOP.cla__DOT__gp1_loop__BRA__22__KET____DOT__gp_inst__DOT__g), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__22__KET____gp_inst.varInsert(__Vfinal,"p", &(TOP.cla__DOT__gp1_loop__BRA__22__KET____DOT__gp_inst__DOT__p), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__23__KET____gp_inst.varInsert(__Vfinal,"a", &(TOP.cla__DOT__gp1_loop__BRA__23__KET____DOT__gp_inst__DOT__a), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__23__KET____gp_inst.varInsert(__Vfinal,"b", &(TOP.cla__DOT__gp1_loop__BRA__23__KET____DOT__gp_inst__DOT__b), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__23__KET____gp_inst.varInsert(__Vfinal,"g", &(TOP.cla__DOT__gp1_loop__BRA__23__KET____DOT__gp_inst__DOT__g), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__23__KET____gp_inst.varInsert(__Vfinal,"p", &(TOP.cla__DOT__gp1_loop__BRA__23__KET____DOT__gp_inst__DOT__p), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__24__KET____gp_inst.varInsert(__Vfinal,"a", &(TOP.cla__DOT__gp1_loop__BRA__24__KET____DOT__gp_inst__DOT__a), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__24__KET____gp_inst.varInsert(__Vfinal,"b", &(TOP.cla__DOT__gp1_loop__BRA__24__KET____DOT__gp_inst__DOT__b), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__24__KET____gp_inst.varInsert(__Vfinal,"g", &(TOP.cla__DOT__gp1_loop__BRA__24__KET____DOT__gp_inst__DOT__g), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__24__KET____gp_inst.varInsert(__Vfinal,"p", &(TOP.cla__DOT__gp1_loop__BRA__24__KET____DOT__gp_inst__DOT__p), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__25__KET____gp_inst.varInsert(__Vfinal,"a", &(TOP.cla__DOT__gp1_loop__BRA__25__KET____DOT__gp_inst__DOT__a), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__25__KET____gp_inst.varInsert(__Vfinal,"b", &(TOP.cla__DOT__gp1_loop__BRA__25__KET____DOT__gp_inst__DOT__b), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__25__KET____gp_inst.varInsert(__Vfinal,"g", &(TOP.cla__DOT__gp1_loop__BRA__25__KET____DOT__gp_inst__DOT__g), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__25__KET____gp_inst.varInsert(__Vfinal,"p", &(TOP.cla__DOT__gp1_loop__BRA__25__KET____DOT__gp_inst__DOT__p), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__26__KET____gp_inst.varInsert(__Vfinal,"a", &(TOP.cla__DOT__gp1_loop__BRA__26__KET____DOT__gp_inst__DOT__a), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__26__KET____gp_inst.varInsert(__Vfinal,"b", &(TOP.cla__DOT__gp1_loop__BRA__26__KET____DOT__gp_inst__DOT__b), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__26__KET____gp_inst.varInsert(__Vfinal,"g", &(TOP.cla__DOT__gp1_loop__BRA__26__KET____DOT__gp_inst__DOT__g), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__26__KET____gp_inst.varInsert(__Vfinal,"p", &(TOP.cla__DOT__gp1_loop__BRA__26__KET____DOT__gp_inst__DOT__p), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__27__KET____gp_inst.varInsert(__Vfinal,"a", &(TOP.cla__DOT__gp1_loop__BRA__27__KET____DOT__gp_inst__DOT__a), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__27__KET____gp_inst.varInsert(__Vfinal,"b", &(TOP.cla__DOT__gp1_loop__BRA__27__KET____DOT__gp_inst__DOT__b), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__27__KET____gp_inst.varInsert(__Vfinal,"g", &(TOP.cla__DOT__gp1_loop__BRA__27__KET____DOT__gp_inst__DOT__g), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__27__KET____gp_inst.varInsert(__Vfinal,"p", &(TOP.cla__DOT__gp1_loop__BRA__27__KET____DOT__gp_inst__DOT__p), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__28__KET____gp_inst.varInsert(__Vfinal,"a", &(TOP.cla__DOT__gp1_loop__BRA__28__KET____DOT__gp_inst__DOT__a), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__28__KET____gp_inst.varInsert(__Vfinal,"b", &(TOP.cla__DOT__gp1_loop__BRA__28__KET____DOT__gp_inst__DOT__b), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__28__KET____gp_inst.varInsert(__Vfinal,"g", &(TOP.cla__DOT__gp1_loop__BRA__28__KET____DOT__gp_inst__DOT__g), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__28__KET____gp_inst.varInsert(__Vfinal,"p", &(TOP.cla__DOT__gp1_loop__BRA__28__KET____DOT__gp_inst__DOT__p), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__29__KET____gp_inst.varInsert(__Vfinal,"a", &(TOP.cla__DOT__gp1_loop__BRA__29__KET____DOT__gp_inst__DOT__a), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__29__KET____gp_inst.varInsert(__Vfinal,"b", &(TOP.cla__DOT__gp1_loop__BRA__29__KET____DOT__gp_inst__DOT__b), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__29__KET____gp_inst.varInsert(__Vfinal,"g", &(TOP.cla__DOT__gp1_loop__BRA__29__KET____DOT__gp_inst__DOT__g), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__29__KET____gp_inst.varInsert(__Vfinal,"p", &(TOP.cla__DOT__gp1_loop__BRA__29__KET____DOT__gp_inst__DOT__p), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__2__KET____gp_inst.varInsert(__Vfinal,"a", &(TOP.cla__DOT__gp1_loop__BRA__2__KET____DOT__gp_inst__DOT__a), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__2__KET____gp_inst.varInsert(__Vfinal,"b", &(TOP.cla__DOT__gp1_loop__BRA__2__KET____DOT__gp_inst__DOT__b), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__2__KET____gp_inst.varInsert(__Vfinal,"g", &(TOP.cla__DOT__gp1_loop__BRA__2__KET____DOT__gp_inst__DOT__g), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__2__KET____gp_inst.varInsert(__Vfinal,"p", &(TOP.cla__DOT__gp1_loop__BRA__2__KET____DOT__gp_inst__DOT__p), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__30__KET____gp_inst.varInsert(__Vfinal,"a", &(TOP.cla__DOT__gp1_loop__BRA__30__KET____DOT__gp_inst__DOT__a), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__30__KET____gp_inst.varInsert(__Vfinal,"b", &(TOP.cla__DOT__gp1_loop__BRA__30__KET____DOT__gp_inst__DOT__b), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__30__KET____gp_inst.varInsert(__Vfinal,"g", &(TOP.cla__DOT__gp1_loop__BRA__30__KET____DOT__gp_inst__DOT__g), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__30__KET____gp_inst.varInsert(__Vfinal,"p", &(TOP.cla__DOT__gp1_loop__BRA__30__KET____DOT__gp_inst__DOT__p), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__31__KET____gp_inst.varInsert(__Vfinal,"a", &(TOP.cla__DOT__gp1_loop__BRA__31__KET____DOT__gp_inst__DOT__a), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__31__KET____gp_inst.varInsert(__Vfinal,"b", &(TOP.cla__DOT__gp1_loop__BRA__31__KET____DOT__gp_inst__DOT__b), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__31__KET____gp_inst.varInsert(__Vfinal,"g", &(TOP.cla__DOT__gp1_loop__BRA__31__KET____DOT__gp_inst__DOT__g), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__31__KET____gp_inst.varInsert(__Vfinal,"p", &(TOP.cla__DOT__gp1_loop__BRA__31__KET____DOT__gp_inst__DOT__p), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__3__KET____gp_inst.varInsert(__Vfinal,"a", &(TOP.cla__DOT__gp1_loop__BRA__3__KET____DOT__gp_inst__DOT__a), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__3__KET____gp_inst.varInsert(__Vfinal,"b", &(TOP.cla__DOT__gp1_loop__BRA__3__KET____DOT__gp_inst__DOT__b), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__3__KET____gp_inst.varInsert(__Vfinal,"g", &(TOP.cla__DOT__gp1_loop__BRA__3__KET____DOT__gp_inst__DOT__g), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__3__KET____gp_inst.varInsert(__Vfinal,"p", &(TOP.cla__DOT__gp1_loop__BRA__3__KET____DOT__gp_inst__DOT__p), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__4__KET____gp_inst.varInsert(__Vfinal,"a", &(TOP.cla__DOT__gp1_loop__BRA__4__KET____DOT__gp_inst__DOT__a), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__4__KET____gp_inst.varInsert(__Vfinal,"b", &(TOP.cla__DOT__gp1_loop__BRA__4__KET____DOT__gp_inst__DOT__b), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__4__KET____gp_inst.varInsert(__Vfinal,"g", &(TOP.cla__DOT__gp1_loop__BRA__4__KET____DOT__gp_inst__DOT__g), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__4__KET____gp_inst.varInsert(__Vfinal,"p", &(TOP.cla__DOT__gp1_loop__BRA__4__KET____DOT__gp_inst__DOT__p), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__5__KET____gp_inst.varInsert(__Vfinal,"a", &(TOP.cla__DOT__gp1_loop__BRA__5__KET____DOT__gp_inst__DOT__a), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__5__KET____gp_inst.varInsert(__Vfinal,"b", &(TOP.cla__DOT__gp1_loop__BRA__5__KET____DOT__gp_inst__DOT__b), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__5__KET____gp_inst.varInsert(__Vfinal,"g", &(TOP.cla__DOT__gp1_loop__BRA__5__KET____DOT__gp_inst__DOT__g), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__5__KET____gp_inst.varInsert(__Vfinal,"p", &(TOP.cla__DOT__gp1_loop__BRA__5__KET____DOT__gp_inst__DOT__p), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__6__KET____gp_inst.varInsert(__Vfinal,"a", &(TOP.cla__DOT__gp1_loop__BRA__6__KET____DOT__gp_inst__DOT__a), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__6__KET____gp_inst.varInsert(__Vfinal,"b", &(TOP.cla__DOT__gp1_loop__BRA__6__KET____DOT__gp_inst__DOT__b), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__6__KET____gp_inst.varInsert(__Vfinal,"g", &(TOP.cla__DOT__gp1_loop__BRA__6__KET____DOT__gp_inst__DOT__g), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__6__KET____gp_inst.varInsert(__Vfinal,"p", &(TOP.cla__DOT__gp1_loop__BRA__6__KET____DOT__gp_inst__DOT__p), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__7__KET____gp_inst.varInsert(__Vfinal,"a", &(TOP.cla__DOT__gp1_loop__BRA__7__KET____DOT__gp_inst__DOT__a), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__7__KET____gp_inst.varInsert(__Vfinal,"b", &(TOP.cla__DOT__gp1_loop__BRA__7__KET____DOT__gp_inst__DOT__b), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__7__KET____gp_inst.varInsert(__Vfinal,"g", &(TOP.cla__DOT__gp1_loop__BRA__7__KET____DOT__gp_inst__DOT__g), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__7__KET____gp_inst.varInsert(__Vfinal,"p", &(TOP.cla__DOT__gp1_loop__BRA__7__KET____DOT__gp_inst__DOT__p), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__8__KET____gp_inst.varInsert(__Vfinal,"a", &(TOP.cla__DOT__gp1_loop__BRA__8__KET____DOT__gp_inst__DOT__a), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__8__KET____gp_inst.varInsert(__Vfinal,"b", &(TOP.cla__DOT__gp1_loop__BRA__8__KET____DOT__gp_inst__DOT__b), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__8__KET____gp_inst.varInsert(__Vfinal,"g", &(TOP.cla__DOT__gp1_loop__BRA__8__KET____DOT__gp_inst__DOT__g), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__8__KET____gp_inst.varInsert(__Vfinal,"p", &(TOP.cla__DOT__gp1_loop__BRA__8__KET____DOT__gp_inst__DOT__p), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__9__KET____gp_inst.varInsert(__Vfinal,"a", &(TOP.cla__DOT__gp1_loop__BRA__9__KET____DOT__gp_inst__DOT__a), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__9__KET____gp_inst.varInsert(__Vfinal,"b", &(TOP.cla__DOT__gp1_loop__BRA__9__KET____DOT__gp_inst__DOT__b), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__9__KET____gp_inst.varInsert(__Vfinal,"g", &(TOP.cla__DOT__gp1_loop__BRA__9__KET____DOT__gp_inst__DOT__g), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp1_loop__BRA__9__KET____gp_inst.varInsert(__Vfinal,"p", &(TOP.cla__DOT__gp1_loop__BRA__9__KET____DOT__gp_inst__DOT__p), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_high.varInsert(__Vfinal,"c_mid", &(TOP.cla__DOT__gp8_high__DOT__c_mid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_high.varInsert(__Vfinal,"cin", &(TOP.cla__DOT__gp8_high__DOT__cin), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_high.varInsert(__Vfinal,"cout", &(TOP.cla__DOT__gp8_high__DOT__cout), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_cla__gp8_high.varInsert(__Vfinal,"g_lower", &(TOP.cla__DOT__gp8_high__DOT__g_lower), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_high.varInsert(__Vfinal,"g_upper", &(TOP.cla__DOT__gp8_high__DOT__g_upper), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_high.varInsert(__Vfinal,"gin", &(TOP.cla__DOT__gp8_high__DOT__gin), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_cla__gp8_high.varInsert(__Vfinal,"gout", &(TOP.cla__DOT__gp8_high__DOT__gout), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_high.varInsert(__Vfinal,"p_lower", &(TOP.cla__DOT__gp8_high__DOT__p_lower), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_high.varInsert(__Vfinal,"p_upper", &(TOP.cla__DOT__gp8_high__DOT__p_upper), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_high.varInsert(__Vfinal,"pin", &(TOP.cla__DOT__gp8_high__DOT__pin), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_cla__gp8_high.varInsert(__Vfinal,"pout", &(TOP.cla__DOT__gp8_high__DOT__pout), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_high__gp_segment_high.varInsert(__Vfinal,"cin", &(TOP.cla__DOT__gp8_high__DOT__gp_segment_high__DOT__cin), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_high__gp_segment_high.varInsert(__Vfinal,"cout", &(TOP.cla__DOT__gp8_high__DOT__gp_segment_high__DOT__cout), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_cla__gp8_high__gp_segment_high.varInsert(__Vfinal,"gin", &(TOP.cla__DOT__gp8_high__DOT__gp_segment_high__DOT__gin), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_cla__gp8_high__gp_segment_high.varInsert(__Vfinal,"gout", &(TOP.cla__DOT__gp8_high__DOT__gp_segment_high__DOT__gout), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_high__gp_segment_high.varInsert(__Vfinal,"pin", &(TOP.cla__DOT__gp8_high__DOT__gp_segment_high__DOT__pin), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_cla__gp8_high__gp_segment_high.varInsert(__Vfinal,"pout", &(TOP.cla__DOT__gp8_high__DOT__gp_segment_high__DOT__pout), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_high__gp_segment_low.varInsert(__Vfinal,"cin", &(TOP.cla__DOT__gp8_high__DOT__gp_segment_low__DOT__cin), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_high__gp_segment_low.varInsert(__Vfinal,"cout", &(TOP.cla__DOT__gp8_high__DOT__gp_segment_low__DOT__cout), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_cla__gp8_high__gp_segment_low.varInsert(__Vfinal,"gin", &(TOP.cla__DOT__gp8_high__DOT__gp_segment_low__DOT__gin), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_cla__gp8_high__gp_segment_low.varInsert(__Vfinal,"gout", &(TOP.cla__DOT__gp8_high__DOT__gp_segment_low__DOT__gout), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_high__gp_segment_low.varInsert(__Vfinal,"pin", &(TOP.cla__DOT__gp8_high__DOT__gp_segment_low__DOT__pin), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_cla__gp8_high__gp_segment_low.varInsert(__Vfinal,"pout", &(TOP.cla__DOT__gp8_high__DOT__gp_segment_low__DOT__pout), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_low.varInsert(__Vfinal,"c_mid", &(TOP.cla__DOT__gp8_low__DOT__c_mid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_low.varInsert(__Vfinal,"cin", &(TOP.cla__DOT__gp8_low__DOT__cin), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_low.varInsert(__Vfinal,"cout", &(TOP.cla__DOT__gp8_low__DOT__cout), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_cla__gp8_low.varInsert(__Vfinal,"g_lower", &(TOP.cla__DOT__gp8_low__DOT__g_lower), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_low.varInsert(__Vfinal,"g_upper", &(TOP.cla__DOT__gp8_low__DOT__g_upper), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_low.varInsert(__Vfinal,"gin", &(TOP.cla__DOT__gp8_low__DOT__gin), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_cla__gp8_low.varInsert(__Vfinal,"gout", &(TOP.cla__DOT__gp8_low__DOT__gout), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_low.varInsert(__Vfinal,"p_lower", &(TOP.cla__DOT__gp8_low__DOT__p_lower), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_low.varInsert(__Vfinal,"p_upper", &(TOP.cla__DOT__gp8_low__DOT__p_upper), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_low.varInsert(__Vfinal,"pin", &(TOP.cla__DOT__gp8_low__DOT__pin), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_cla__gp8_low.varInsert(__Vfinal,"pout", &(TOP.cla__DOT__gp8_low__DOT__pout), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_low__gp_segment_high.varInsert(__Vfinal,"cin", &(TOP.cla__DOT__gp8_low__DOT__gp_segment_high__DOT__cin), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_low__gp_segment_high.varInsert(__Vfinal,"cout", &(TOP.cla__DOT__gp8_low__DOT__gp_segment_high__DOT__cout), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_cla__gp8_low__gp_segment_high.varInsert(__Vfinal,"gin", &(TOP.cla__DOT__gp8_low__DOT__gp_segment_high__DOT__gin), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_cla__gp8_low__gp_segment_high.varInsert(__Vfinal,"gout", &(TOP.cla__DOT__gp8_low__DOT__gp_segment_high__DOT__gout), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_low__gp_segment_high.varInsert(__Vfinal,"pin", &(TOP.cla__DOT__gp8_low__DOT__gp_segment_high__DOT__pin), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_cla__gp8_low__gp_segment_high.varInsert(__Vfinal,"pout", &(TOP.cla__DOT__gp8_low__DOT__gp_segment_high__DOT__pout), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_low__gp_segment_low.varInsert(__Vfinal,"cin", &(TOP.cla__DOT__gp8_low__DOT__gp_segment_low__DOT__cin), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_low__gp_segment_low.varInsert(__Vfinal,"cout", &(TOP.cla__DOT__gp8_low__DOT__gp_segment_low__DOT__cout), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_cla__gp8_low__gp_segment_low.varInsert(__Vfinal,"gin", &(TOP.cla__DOT__gp8_low__DOT__gp_segment_low__DOT__gin), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_cla__gp8_low__gp_segment_low.varInsert(__Vfinal,"gout", &(TOP.cla__DOT__gp8_low__DOT__gp_segment_low__DOT__gout), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_low__gp_segment_low.varInsert(__Vfinal,"pin", &(TOP.cla__DOT__gp8_low__DOT__gp_segment_low__DOT__pin), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_cla__gp8_low__gp_segment_low.varInsert(__Vfinal,"pout", &(TOP.cla__DOT__gp8_low__DOT__gp_segment_low__DOT__pout), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_mid1.varInsert(__Vfinal,"c_mid", &(TOP.cla__DOT__gp8_mid1__DOT__c_mid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_mid1.varInsert(__Vfinal,"cin", &(TOP.cla__DOT__gp8_mid1__DOT__cin), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_mid1.varInsert(__Vfinal,"cout", &(TOP.cla__DOT__gp8_mid1__DOT__cout), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_cla__gp8_mid1.varInsert(__Vfinal,"g_lower", &(TOP.cla__DOT__gp8_mid1__DOT__g_lower), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_mid1.varInsert(__Vfinal,"g_upper", &(TOP.cla__DOT__gp8_mid1__DOT__g_upper), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_mid1.varInsert(__Vfinal,"gin", &(TOP.cla__DOT__gp8_mid1__DOT__gin), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_cla__gp8_mid1.varInsert(__Vfinal,"gout", &(TOP.cla__DOT__gp8_mid1__DOT__gout), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_mid1.varInsert(__Vfinal,"p_lower", &(TOP.cla__DOT__gp8_mid1__DOT__p_lower), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_mid1.varInsert(__Vfinal,"p_upper", &(TOP.cla__DOT__gp8_mid1__DOT__p_upper), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_mid1.varInsert(__Vfinal,"pin", &(TOP.cla__DOT__gp8_mid1__DOT__pin), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_cla__gp8_mid1.varInsert(__Vfinal,"pout", &(TOP.cla__DOT__gp8_mid1__DOT__pout), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_mid1__gp_segment_high.varInsert(__Vfinal,"cin", &(TOP.cla__DOT__gp8_mid1__DOT__gp_segment_high__DOT__cin), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_mid1__gp_segment_high.varInsert(__Vfinal,"cout", &(TOP.cla__DOT__gp8_mid1__DOT__gp_segment_high__DOT__cout), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_cla__gp8_mid1__gp_segment_high.varInsert(__Vfinal,"gin", &(TOP.cla__DOT__gp8_mid1__DOT__gp_segment_high__DOT__gin), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_cla__gp8_mid1__gp_segment_high.varInsert(__Vfinal,"gout", &(TOP.cla__DOT__gp8_mid1__DOT__gp_segment_high__DOT__gout), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_mid1__gp_segment_high.varInsert(__Vfinal,"pin", &(TOP.cla__DOT__gp8_mid1__DOT__gp_segment_high__DOT__pin), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_cla__gp8_mid1__gp_segment_high.varInsert(__Vfinal,"pout", &(TOP.cla__DOT__gp8_mid1__DOT__gp_segment_high__DOT__pout), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_mid1__gp_segment_low.varInsert(__Vfinal,"cin", &(TOP.cla__DOT__gp8_mid1__DOT__gp_segment_low__DOT__cin), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_mid1__gp_segment_low.varInsert(__Vfinal,"cout", &(TOP.cla__DOT__gp8_mid1__DOT__gp_segment_low__DOT__cout), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_cla__gp8_mid1__gp_segment_low.varInsert(__Vfinal,"gin", &(TOP.cla__DOT__gp8_mid1__DOT__gp_segment_low__DOT__gin), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_cla__gp8_mid1__gp_segment_low.varInsert(__Vfinal,"gout", &(TOP.cla__DOT__gp8_mid1__DOT__gp_segment_low__DOT__gout), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_mid1__gp_segment_low.varInsert(__Vfinal,"pin", &(TOP.cla__DOT__gp8_mid1__DOT__gp_segment_low__DOT__pin), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_cla__gp8_mid1__gp_segment_low.varInsert(__Vfinal,"pout", &(TOP.cla__DOT__gp8_mid1__DOT__gp_segment_low__DOT__pout), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_mid2.varInsert(__Vfinal,"c_mid", &(TOP.cla__DOT__gp8_mid2__DOT__c_mid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_mid2.varInsert(__Vfinal,"cin", &(TOP.cla__DOT__gp8_mid2__DOT__cin), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_mid2.varInsert(__Vfinal,"cout", &(TOP.cla__DOT__gp8_mid2__DOT__cout), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_cla__gp8_mid2.varInsert(__Vfinal,"g_lower", &(TOP.cla__DOT__gp8_mid2__DOT__g_lower), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_mid2.varInsert(__Vfinal,"g_upper", &(TOP.cla__DOT__gp8_mid2__DOT__g_upper), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_mid2.varInsert(__Vfinal,"gin", &(TOP.cla__DOT__gp8_mid2__DOT__gin), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_cla__gp8_mid2.varInsert(__Vfinal,"gout", &(TOP.cla__DOT__gp8_mid2__DOT__gout), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_mid2.varInsert(__Vfinal,"p_lower", &(TOP.cla__DOT__gp8_mid2__DOT__p_lower), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_mid2.varInsert(__Vfinal,"p_upper", &(TOP.cla__DOT__gp8_mid2__DOT__p_upper), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_mid2.varInsert(__Vfinal,"pin", &(TOP.cla__DOT__gp8_mid2__DOT__pin), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_cla__gp8_mid2.varInsert(__Vfinal,"pout", &(TOP.cla__DOT__gp8_mid2__DOT__pout), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_mid2__gp_segment_high.varInsert(__Vfinal,"cin", &(TOP.cla__DOT__gp8_mid2__DOT__gp_segment_high__DOT__cin), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_mid2__gp_segment_high.varInsert(__Vfinal,"cout", &(TOP.cla__DOT__gp8_mid2__DOT__gp_segment_high__DOT__cout), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_cla__gp8_mid2__gp_segment_high.varInsert(__Vfinal,"gin", &(TOP.cla__DOT__gp8_mid2__DOT__gp_segment_high__DOT__gin), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_cla__gp8_mid2__gp_segment_high.varInsert(__Vfinal,"gout", &(TOP.cla__DOT__gp8_mid2__DOT__gp_segment_high__DOT__gout), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_mid2__gp_segment_high.varInsert(__Vfinal,"pin", &(TOP.cla__DOT__gp8_mid2__DOT__gp_segment_high__DOT__pin), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_cla__gp8_mid2__gp_segment_high.varInsert(__Vfinal,"pout", &(TOP.cla__DOT__gp8_mid2__DOT__gp_segment_high__DOT__pout), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_mid2__gp_segment_low.varInsert(__Vfinal,"cin", &(TOP.cla__DOT__gp8_mid2__DOT__gp_segment_low__DOT__cin), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_mid2__gp_segment_low.varInsert(__Vfinal,"cout", &(TOP.cla__DOT__gp8_mid2__DOT__gp_segment_low__DOT__cout), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_cla__gp8_mid2__gp_segment_low.varInsert(__Vfinal,"gin", &(TOP.cla__DOT__gp8_mid2__DOT__gp_segment_low__DOT__gin), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_cla__gp8_mid2__gp_segment_low.varInsert(__Vfinal,"gout", &(TOP.cla__DOT__gp8_mid2__DOT__gp_segment_low__DOT__gout), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_cla__gp8_mid2__gp_segment_low.varInsert(__Vfinal,"pin", &(TOP.cla__DOT__gp8_mid2__DOT__gp_segment_low__DOT__pin), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_cla__gp8_mid2__gp_segment_low.varInsert(__Vfinal,"pout", &(TOP.cla__DOT__gp8_mid2__DOT__gp_segment_low__DOT__pout), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
    }
}
