// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_fst_c.h"
#include "Vtop__Syms.h"


VL_ATTR_COLD void Vtop___024root__trace_init_sub__TOP__0(Vtop___024root* vlSelf, VerilatedFst* tracep) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_sub__TOP__0\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBus(c+1,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+2,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+3,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+4,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("cla", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+5,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+6,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+7,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+8,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+9,0,"g",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+10,0,"p",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+11,0,"carry",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+12,0,"gout",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+13,0,"pout",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+14,0,"c8",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+15,0,"c16",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+16,0,"c24",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->pushPrefix("gp1_loop[0]", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("gp_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+17,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+18,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+19,0,"g",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+20,0,"p",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("gp1_loop[10]", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("gp_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+21,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+22,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+23,0,"g",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+24,0,"p",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("gp1_loop[11]", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("gp_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+25,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+26,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+27,0,"g",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+28,0,"p",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("gp1_loop[12]", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("gp_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+29,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+30,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+31,0,"g",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+32,0,"p",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("gp1_loop[13]", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("gp_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+33,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+34,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+35,0,"g",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+36,0,"p",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("gp1_loop[14]", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("gp_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+37,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+38,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+39,0,"g",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+40,0,"p",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("gp1_loop[15]", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("gp_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+41,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+42,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+43,0,"g",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+44,0,"p",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("gp1_loop[16]", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("gp_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+45,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+46,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+47,0,"g",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+48,0,"p",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("gp1_loop[17]", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("gp_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+49,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+50,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+51,0,"g",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+52,0,"p",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("gp1_loop[18]", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("gp_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+53,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+54,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+55,0,"g",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+56,0,"p",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("gp1_loop[19]", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("gp_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+57,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+58,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+59,0,"g",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+60,0,"p",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("gp1_loop[1]", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("gp_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+61,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+62,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+63,0,"g",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+64,0,"p",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("gp1_loop[20]", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("gp_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+65,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+66,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+67,0,"g",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+68,0,"p",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("gp1_loop[21]", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("gp_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+69,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+70,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+71,0,"g",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+72,0,"p",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("gp1_loop[22]", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("gp_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+73,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+74,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+75,0,"g",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+76,0,"p",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("gp1_loop[23]", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("gp_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+77,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+78,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+79,0,"g",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+80,0,"p",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("gp1_loop[24]", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("gp_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+81,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+82,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+83,0,"g",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+84,0,"p",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("gp1_loop[25]", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("gp_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+85,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+86,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+87,0,"g",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+88,0,"p",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("gp1_loop[26]", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("gp_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+89,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+90,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+91,0,"g",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+92,0,"p",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("gp1_loop[27]", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("gp_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+93,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+94,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+95,0,"g",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+96,0,"p",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("gp1_loop[28]", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("gp_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+97,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+98,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+99,0,"g",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+100,0,"p",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("gp1_loop[29]", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("gp_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+101,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+102,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+103,0,"g",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+104,0,"p",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("gp1_loop[2]", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("gp_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+105,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+106,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+107,0,"g",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+108,0,"p",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("gp1_loop[30]", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("gp_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+109,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+110,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+111,0,"g",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+112,0,"p",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("gp1_loop[31]", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("gp_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+113,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+114,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+115,0,"g",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+116,0,"p",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("gp1_loop[3]", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("gp_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+117,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+118,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+119,0,"g",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+120,0,"p",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("gp1_loop[4]", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("gp_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+121,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+122,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+123,0,"g",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+124,0,"p",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("gp1_loop[5]", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("gp_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+125,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+126,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+127,0,"g",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+128,0,"p",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("gp1_loop[6]", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("gp_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+129,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+130,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+131,0,"g",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+132,0,"p",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("gp1_loop[7]", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("gp_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+133,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+134,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+135,0,"g",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+136,0,"p",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("gp1_loop[8]", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("gp_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+137,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+138,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+139,0,"g",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+140,0,"p",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("gp1_loop[9]", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("gp_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+141,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+142,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+143,0,"g",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+144,0,"p",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("gp8_high", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+145,0,"gin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+146,0,"pin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+147,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+148,0,"gout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+149,0,"pout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+150,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBit(c+151,0,"g_lower",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+152,0,"p_lower",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+153,0,"g_upper",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+154,0,"p_upper",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+155,0,"c_mid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->pushPrefix("gp_segment_high", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+156,0,"gin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+157,0,"pin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+158,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+159,0,"gout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+160,0,"pout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+161,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->popPrefix();
    tracep->pushPrefix("gp_segment_low", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+162,0,"gin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+163,0,"pin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+164,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+165,0,"gout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+166,0,"pout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+167,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("gp8_low", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+168,0,"gin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+169,0,"pin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+170,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+171,0,"gout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+172,0,"pout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+173,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBit(c+174,0,"g_lower",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+175,0,"p_lower",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+176,0,"g_upper",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+177,0,"p_upper",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+178,0,"c_mid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->pushPrefix("gp_segment_high", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+179,0,"gin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+180,0,"pin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+181,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+182,0,"gout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+183,0,"pout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+184,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->popPrefix();
    tracep->pushPrefix("gp_segment_low", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+185,0,"gin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+186,0,"pin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+187,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+188,0,"gout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+189,0,"pout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+190,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("gp8_mid1", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+191,0,"gin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+192,0,"pin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+193,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+194,0,"gout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+195,0,"pout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+196,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBit(c+197,0,"g_lower",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+198,0,"p_lower",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+199,0,"g_upper",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+200,0,"p_upper",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+201,0,"c_mid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->pushPrefix("gp_segment_high", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+202,0,"gin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+203,0,"pin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+204,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+205,0,"gout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+206,0,"pout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+207,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->popPrefix();
    tracep->pushPrefix("gp_segment_low", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+208,0,"gin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+209,0,"pin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+210,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+211,0,"gout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+212,0,"pout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+213,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("gp8_mid2", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+214,0,"gin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+215,0,"pin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+216,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+217,0,"gout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+218,0,"pout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+219,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBit(c+220,0,"g_lower",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+221,0,"p_lower",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+222,0,"g_upper",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+223,0,"p_upper",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+224,0,"c_mid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->pushPrefix("gp_segment_high", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+225,0,"gin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+226,0,"pin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+227,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+228,0,"gout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+229,0,"pout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+230,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->popPrefix();
    tracep->pushPrefix("gp_segment_low", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+231,0,"gin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+232,0,"pin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+233,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+234,0,"gout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+235,0,"pout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+236,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->popPrefix();
}

VL_ATTR_COLD void Vtop___024root__trace_init_top(Vtop___024root* vlSelf, VerilatedFst* tracep) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_top\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    Vtop___024root__trace_init_sub__TOP__0(vlSelf, tracep);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0(void* voidSelf, VerilatedFst::Buffer* bufp);
VL_ATTR_COLD void Vtop___024root__trace_full_0(void* voidSelf, VerilatedFst::Buffer* bufp);
void Vtop___024root__trace_chg_0(void* voidSelf, VerilatedFst::Buffer* bufp);
void Vtop___024root__trace_cleanup(void* voidSelf, VerilatedFst* /*unused*/);

VL_ATTR_COLD void Vtop___024root__trace_register(Vtop___024root* vlSelf, VerilatedFst* tracep) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_register\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    tracep->addConstCb(&Vtop___024root__trace_const_0, 0U, vlSelf);
    tracep->addFullCb(&Vtop___024root__trace_full_0, 0U, vlSelf);
    tracep->addChgCb(&Vtop___024root__trace_chg_0, 0U, vlSelf);
    tracep->addCleanupCb(&Vtop___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0(void* voidSelf, VerilatedFst::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_const_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
}

VL_ATTR_COLD void Vtop___024root__trace_full_0_sub_0(Vtop___024root* vlSelf, VerilatedFst::Buffer* bufp);

VL_ATTR_COLD void Vtop___024root__trace_full_0(void* voidSelf, VerilatedFst::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vtop___024root__trace_full_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtop___024root__trace_full_0_sub_0(Vtop___024root* vlSelf, VerilatedFst::Buffer* bufp) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_0_sub_0\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullIData(oldp+1,(vlSelfRef.a),32);
    bufp->fullIData(oldp+2,(vlSelfRef.b),32);
    bufp->fullBit(oldp+3,(vlSelfRef.cin));
    bufp->fullIData(oldp+4,(vlSelfRef.sum),32);
    bufp->fullIData(oldp+5,(vlSelfRef.cla__DOT__a),32);
    bufp->fullIData(oldp+6,(vlSelfRef.cla__DOT__b),32);
    bufp->fullBit(oldp+7,(vlSelfRef.cla__DOT__cin));
    bufp->fullIData(oldp+8,(vlSelfRef.cla__DOT__sum),32);
    bufp->fullIData(oldp+9,(vlSelfRef.cla__DOT__g),32);
    bufp->fullIData(oldp+10,(vlSelfRef.cla__DOT__p),32);
    bufp->fullIData(oldp+11,(vlSelfRef.cla__DOT__carry),32);
    bufp->fullCData(oldp+12,(vlSelfRef.cla__DOT__gout),4);
    bufp->fullCData(oldp+13,(vlSelfRef.cla__DOT__pout),4);
    bufp->fullBit(oldp+14,(vlSelfRef.cla__DOT__c8));
    bufp->fullBit(oldp+15,(vlSelfRef.cla__DOT__c16));
    bufp->fullBit(oldp+16,(vlSelfRef.cla__DOT__c24));
    bufp->fullBit(oldp+17,(vlSelfRef.cla__DOT__gp1_loop__BRA__0__KET____DOT__gp_inst__DOT__a));
    bufp->fullBit(oldp+18,(vlSelfRef.cla__DOT__gp1_loop__BRA__0__KET____DOT__gp_inst__DOT__b));
    bufp->fullBit(oldp+19,(vlSelfRef.cla__DOT__gp1_loop__BRA__0__KET____DOT__gp_inst__DOT__g));
    bufp->fullBit(oldp+20,(vlSelfRef.cla__DOT__gp1_loop__BRA__0__KET____DOT__gp_inst__DOT__p));
    bufp->fullBit(oldp+21,(vlSelfRef.cla__DOT__gp1_loop__BRA__10__KET____DOT__gp_inst__DOT__a));
    bufp->fullBit(oldp+22,(vlSelfRef.cla__DOT__gp1_loop__BRA__10__KET____DOT__gp_inst__DOT__b));
    bufp->fullBit(oldp+23,(vlSelfRef.cla__DOT__gp1_loop__BRA__10__KET____DOT__gp_inst__DOT__g));
    bufp->fullBit(oldp+24,(vlSelfRef.cla__DOT__gp1_loop__BRA__10__KET____DOT__gp_inst__DOT__p));
    bufp->fullBit(oldp+25,(vlSelfRef.cla__DOT__gp1_loop__BRA__11__KET____DOT__gp_inst__DOT__a));
    bufp->fullBit(oldp+26,(vlSelfRef.cla__DOT__gp1_loop__BRA__11__KET____DOT__gp_inst__DOT__b));
    bufp->fullBit(oldp+27,(vlSelfRef.cla__DOT__gp1_loop__BRA__11__KET____DOT__gp_inst__DOT__g));
    bufp->fullBit(oldp+28,(vlSelfRef.cla__DOT__gp1_loop__BRA__11__KET____DOT__gp_inst__DOT__p));
    bufp->fullBit(oldp+29,(vlSelfRef.cla__DOT__gp1_loop__BRA__12__KET____DOT__gp_inst__DOT__a));
    bufp->fullBit(oldp+30,(vlSelfRef.cla__DOT__gp1_loop__BRA__12__KET____DOT__gp_inst__DOT__b));
    bufp->fullBit(oldp+31,(vlSelfRef.cla__DOT__gp1_loop__BRA__12__KET____DOT__gp_inst__DOT__g));
    bufp->fullBit(oldp+32,(vlSelfRef.cla__DOT__gp1_loop__BRA__12__KET____DOT__gp_inst__DOT__p));
    bufp->fullBit(oldp+33,(vlSelfRef.cla__DOT__gp1_loop__BRA__13__KET____DOT__gp_inst__DOT__a));
    bufp->fullBit(oldp+34,(vlSelfRef.cla__DOT__gp1_loop__BRA__13__KET____DOT__gp_inst__DOT__b));
    bufp->fullBit(oldp+35,(vlSelfRef.cla__DOT__gp1_loop__BRA__13__KET____DOT__gp_inst__DOT__g));
    bufp->fullBit(oldp+36,(vlSelfRef.cla__DOT__gp1_loop__BRA__13__KET____DOT__gp_inst__DOT__p));
    bufp->fullBit(oldp+37,(vlSelfRef.cla__DOT__gp1_loop__BRA__14__KET____DOT__gp_inst__DOT__a));
    bufp->fullBit(oldp+38,(vlSelfRef.cla__DOT__gp1_loop__BRA__14__KET____DOT__gp_inst__DOT__b));
    bufp->fullBit(oldp+39,(vlSelfRef.cla__DOT__gp1_loop__BRA__14__KET____DOT__gp_inst__DOT__g));
    bufp->fullBit(oldp+40,(vlSelfRef.cla__DOT__gp1_loop__BRA__14__KET____DOT__gp_inst__DOT__p));
    bufp->fullBit(oldp+41,(vlSelfRef.cla__DOT__gp1_loop__BRA__15__KET____DOT__gp_inst__DOT__a));
    bufp->fullBit(oldp+42,(vlSelfRef.cla__DOT__gp1_loop__BRA__15__KET____DOT__gp_inst__DOT__b));
    bufp->fullBit(oldp+43,(vlSelfRef.cla__DOT__gp1_loop__BRA__15__KET____DOT__gp_inst__DOT__g));
    bufp->fullBit(oldp+44,(vlSelfRef.cla__DOT__gp1_loop__BRA__15__KET____DOT__gp_inst__DOT__p));
    bufp->fullBit(oldp+45,(vlSelfRef.cla__DOT__gp1_loop__BRA__16__KET____DOT__gp_inst__DOT__a));
    bufp->fullBit(oldp+46,(vlSelfRef.cla__DOT__gp1_loop__BRA__16__KET____DOT__gp_inst__DOT__b));
    bufp->fullBit(oldp+47,(vlSelfRef.cla__DOT__gp1_loop__BRA__16__KET____DOT__gp_inst__DOT__g));
    bufp->fullBit(oldp+48,(vlSelfRef.cla__DOT__gp1_loop__BRA__16__KET____DOT__gp_inst__DOT__p));
    bufp->fullBit(oldp+49,(vlSelfRef.cla__DOT__gp1_loop__BRA__17__KET____DOT__gp_inst__DOT__a));
    bufp->fullBit(oldp+50,(vlSelfRef.cla__DOT__gp1_loop__BRA__17__KET____DOT__gp_inst__DOT__b));
    bufp->fullBit(oldp+51,(vlSelfRef.cla__DOT__gp1_loop__BRA__17__KET____DOT__gp_inst__DOT__g));
    bufp->fullBit(oldp+52,(vlSelfRef.cla__DOT__gp1_loop__BRA__17__KET____DOT__gp_inst__DOT__p));
    bufp->fullBit(oldp+53,(vlSelfRef.cla__DOT__gp1_loop__BRA__18__KET____DOT__gp_inst__DOT__a));
    bufp->fullBit(oldp+54,(vlSelfRef.cla__DOT__gp1_loop__BRA__18__KET____DOT__gp_inst__DOT__b));
    bufp->fullBit(oldp+55,(vlSelfRef.cla__DOT__gp1_loop__BRA__18__KET____DOT__gp_inst__DOT__g));
    bufp->fullBit(oldp+56,(vlSelfRef.cla__DOT__gp1_loop__BRA__18__KET____DOT__gp_inst__DOT__p));
    bufp->fullBit(oldp+57,(vlSelfRef.cla__DOT__gp1_loop__BRA__19__KET____DOT__gp_inst__DOT__a));
    bufp->fullBit(oldp+58,(vlSelfRef.cla__DOT__gp1_loop__BRA__19__KET____DOT__gp_inst__DOT__b));
    bufp->fullBit(oldp+59,(vlSelfRef.cla__DOT__gp1_loop__BRA__19__KET____DOT__gp_inst__DOT__g));
    bufp->fullBit(oldp+60,(vlSelfRef.cla__DOT__gp1_loop__BRA__19__KET____DOT__gp_inst__DOT__p));
    bufp->fullBit(oldp+61,(vlSelfRef.cla__DOT__gp1_loop__BRA__1__KET____DOT__gp_inst__DOT__a));
    bufp->fullBit(oldp+62,(vlSelfRef.cla__DOT__gp1_loop__BRA__1__KET____DOT__gp_inst__DOT__b));
    bufp->fullBit(oldp+63,(vlSelfRef.cla__DOT__gp1_loop__BRA__1__KET____DOT__gp_inst__DOT__g));
    bufp->fullBit(oldp+64,(vlSelfRef.cla__DOT__gp1_loop__BRA__1__KET____DOT__gp_inst__DOT__p));
    bufp->fullBit(oldp+65,(vlSelfRef.cla__DOT__gp1_loop__BRA__20__KET____DOT__gp_inst__DOT__a));
    bufp->fullBit(oldp+66,(vlSelfRef.cla__DOT__gp1_loop__BRA__20__KET____DOT__gp_inst__DOT__b));
    bufp->fullBit(oldp+67,(vlSelfRef.cla__DOT__gp1_loop__BRA__20__KET____DOT__gp_inst__DOT__g));
    bufp->fullBit(oldp+68,(vlSelfRef.cla__DOT__gp1_loop__BRA__20__KET____DOT__gp_inst__DOT__p));
    bufp->fullBit(oldp+69,(vlSelfRef.cla__DOT__gp1_loop__BRA__21__KET____DOT__gp_inst__DOT__a));
    bufp->fullBit(oldp+70,(vlSelfRef.cla__DOT__gp1_loop__BRA__21__KET____DOT__gp_inst__DOT__b));
    bufp->fullBit(oldp+71,(vlSelfRef.cla__DOT__gp1_loop__BRA__21__KET____DOT__gp_inst__DOT__g));
    bufp->fullBit(oldp+72,(vlSelfRef.cla__DOT__gp1_loop__BRA__21__KET____DOT__gp_inst__DOT__p));
    bufp->fullBit(oldp+73,(vlSelfRef.cla__DOT__gp1_loop__BRA__22__KET____DOT__gp_inst__DOT__a));
    bufp->fullBit(oldp+74,(vlSelfRef.cla__DOT__gp1_loop__BRA__22__KET____DOT__gp_inst__DOT__b));
    bufp->fullBit(oldp+75,(vlSelfRef.cla__DOT__gp1_loop__BRA__22__KET____DOT__gp_inst__DOT__g));
    bufp->fullBit(oldp+76,(vlSelfRef.cla__DOT__gp1_loop__BRA__22__KET____DOT__gp_inst__DOT__p));
    bufp->fullBit(oldp+77,(vlSelfRef.cla__DOT__gp1_loop__BRA__23__KET____DOT__gp_inst__DOT__a));
    bufp->fullBit(oldp+78,(vlSelfRef.cla__DOT__gp1_loop__BRA__23__KET____DOT__gp_inst__DOT__b));
    bufp->fullBit(oldp+79,(vlSelfRef.cla__DOT__gp1_loop__BRA__23__KET____DOT__gp_inst__DOT__g));
    bufp->fullBit(oldp+80,(vlSelfRef.cla__DOT__gp1_loop__BRA__23__KET____DOT__gp_inst__DOT__p));
    bufp->fullBit(oldp+81,(vlSelfRef.cla__DOT__gp1_loop__BRA__24__KET____DOT__gp_inst__DOT__a));
    bufp->fullBit(oldp+82,(vlSelfRef.cla__DOT__gp1_loop__BRA__24__KET____DOT__gp_inst__DOT__b));
    bufp->fullBit(oldp+83,(vlSelfRef.cla__DOT__gp1_loop__BRA__24__KET____DOT__gp_inst__DOT__g));
    bufp->fullBit(oldp+84,(vlSelfRef.cla__DOT__gp1_loop__BRA__24__KET____DOT__gp_inst__DOT__p));
    bufp->fullBit(oldp+85,(vlSelfRef.cla__DOT__gp1_loop__BRA__25__KET____DOT__gp_inst__DOT__a));
    bufp->fullBit(oldp+86,(vlSelfRef.cla__DOT__gp1_loop__BRA__25__KET____DOT__gp_inst__DOT__b));
    bufp->fullBit(oldp+87,(vlSelfRef.cla__DOT__gp1_loop__BRA__25__KET____DOT__gp_inst__DOT__g));
    bufp->fullBit(oldp+88,(vlSelfRef.cla__DOT__gp1_loop__BRA__25__KET____DOT__gp_inst__DOT__p));
    bufp->fullBit(oldp+89,(vlSelfRef.cla__DOT__gp1_loop__BRA__26__KET____DOT__gp_inst__DOT__a));
    bufp->fullBit(oldp+90,(vlSelfRef.cla__DOT__gp1_loop__BRA__26__KET____DOT__gp_inst__DOT__b));
    bufp->fullBit(oldp+91,(vlSelfRef.cla__DOT__gp1_loop__BRA__26__KET____DOT__gp_inst__DOT__g));
    bufp->fullBit(oldp+92,(vlSelfRef.cla__DOT__gp1_loop__BRA__26__KET____DOT__gp_inst__DOT__p));
    bufp->fullBit(oldp+93,(vlSelfRef.cla__DOT__gp1_loop__BRA__27__KET____DOT__gp_inst__DOT__a));
    bufp->fullBit(oldp+94,(vlSelfRef.cla__DOT__gp1_loop__BRA__27__KET____DOT__gp_inst__DOT__b));
    bufp->fullBit(oldp+95,(vlSelfRef.cla__DOT__gp1_loop__BRA__27__KET____DOT__gp_inst__DOT__g));
    bufp->fullBit(oldp+96,(vlSelfRef.cla__DOT__gp1_loop__BRA__27__KET____DOT__gp_inst__DOT__p));
    bufp->fullBit(oldp+97,(vlSelfRef.cla__DOT__gp1_loop__BRA__28__KET____DOT__gp_inst__DOT__a));
    bufp->fullBit(oldp+98,(vlSelfRef.cla__DOT__gp1_loop__BRA__28__KET____DOT__gp_inst__DOT__b));
    bufp->fullBit(oldp+99,(vlSelfRef.cla__DOT__gp1_loop__BRA__28__KET____DOT__gp_inst__DOT__g));
    bufp->fullBit(oldp+100,(vlSelfRef.cla__DOT__gp1_loop__BRA__28__KET____DOT__gp_inst__DOT__p));
    bufp->fullBit(oldp+101,(vlSelfRef.cla__DOT__gp1_loop__BRA__29__KET____DOT__gp_inst__DOT__a));
    bufp->fullBit(oldp+102,(vlSelfRef.cla__DOT__gp1_loop__BRA__29__KET____DOT__gp_inst__DOT__b));
    bufp->fullBit(oldp+103,(vlSelfRef.cla__DOT__gp1_loop__BRA__29__KET____DOT__gp_inst__DOT__g));
    bufp->fullBit(oldp+104,(vlSelfRef.cla__DOT__gp1_loop__BRA__29__KET____DOT__gp_inst__DOT__p));
    bufp->fullBit(oldp+105,(vlSelfRef.cla__DOT__gp1_loop__BRA__2__KET____DOT__gp_inst__DOT__a));
    bufp->fullBit(oldp+106,(vlSelfRef.cla__DOT__gp1_loop__BRA__2__KET____DOT__gp_inst__DOT__b));
    bufp->fullBit(oldp+107,(vlSelfRef.cla__DOT__gp1_loop__BRA__2__KET____DOT__gp_inst__DOT__g));
    bufp->fullBit(oldp+108,(vlSelfRef.cla__DOT__gp1_loop__BRA__2__KET____DOT__gp_inst__DOT__p));
    bufp->fullBit(oldp+109,(vlSelfRef.cla__DOT__gp1_loop__BRA__30__KET____DOT__gp_inst__DOT__a));
    bufp->fullBit(oldp+110,(vlSelfRef.cla__DOT__gp1_loop__BRA__30__KET____DOT__gp_inst__DOT__b));
    bufp->fullBit(oldp+111,(vlSelfRef.cla__DOT__gp1_loop__BRA__30__KET____DOT__gp_inst__DOT__g));
    bufp->fullBit(oldp+112,(vlSelfRef.cla__DOT__gp1_loop__BRA__30__KET____DOT__gp_inst__DOT__p));
    bufp->fullBit(oldp+113,(vlSelfRef.cla__DOT__gp1_loop__BRA__31__KET____DOT__gp_inst__DOT__a));
    bufp->fullBit(oldp+114,(vlSelfRef.cla__DOT__gp1_loop__BRA__31__KET____DOT__gp_inst__DOT__b));
    bufp->fullBit(oldp+115,(vlSelfRef.cla__DOT__gp1_loop__BRA__31__KET____DOT__gp_inst__DOT__g));
    bufp->fullBit(oldp+116,(vlSelfRef.cla__DOT__gp1_loop__BRA__31__KET____DOT__gp_inst__DOT__p));
    bufp->fullBit(oldp+117,(vlSelfRef.cla__DOT__gp1_loop__BRA__3__KET____DOT__gp_inst__DOT__a));
    bufp->fullBit(oldp+118,(vlSelfRef.cla__DOT__gp1_loop__BRA__3__KET____DOT__gp_inst__DOT__b));
    bufp->fullBit(oldp+119,(vlSelfRef.cla__DOT__gp1_loop__BRA__3__KET____DOT__gp_inst__DOT__g));
    bufp->fullBit(oldp+120,(vlSelfRef.cla__DOT__gp1_loop__BRA__3__KET____DOT__gp_inst__DOT__p));
    bufp->fullBit(oldp+121,(vlSelfRef.cla__DOT__gp1_loop__BRA__4__KET____DOT__gp_inst__DOT__a));
    bufp->fullBit(oldp+122,(vlSelfRef.cla__DOT__gp1_loop__BRA__4__KET____DOT__gp_inst__DOT__b));
    bufp->fullBit(oldp+123,(vlSelfRef.cla__DOT__gp1_loop__BRA__4__KET____DOT__gp_inst__DOT__g));
    bufp->fullBit(oldp+124,(vlSelfRef.cla__DOT__gp1_loop__BRA__4__KET____DOT__gp_inst__DOT__p));
    bufp->fullBit(oldp+125,(vlSelfRef.cla__DOT__gp1_loop__BRA__5__KET____DOT__gp_inst__DOT__a));
    bufp->fullBit(oldp+126,(vlSelfRef.cla__DOT__gp1_loop__BRA__5__KET____DOT__gp_inst__DOT__b));
    bufp->fullBit(oldp+127,(vlSelfRef.cla__DOT__gp1_loop__BRA__5__KET____DOT__gp_inst__DOT__g));
    bufp->fullBit(oldp+128,(vlSelfRef.cla__DOT__gp1_loop__BRA__5__KET____DOT__gp_inst__DOT__p));
    bufp->fullBit(oldp+129,(vlSelfRef.cla__DOT__gp1_loop__BRA__6__KET____DOT__gp_inst__DOT__a));
    bufp->fullBit(oldp+130,(vlSelfRef.cla__DOT__gp1_loop__BRA__6__KET____DOT__gp_inst__DOT__b));
    bufp->fullBit(oldp+131,(vlSelfRef.cla__DOT__gp1_loop__BRA__6__KET____DOT__gp_inst__DOT__g));
    bufp->fullBit(oldp+132,(vlSelfRef.cla__DOT__gp1_loop__BRA__6__KET____DOT__gp_inst__DOT__p));
    bufp->fullBit(oldp+133,(vlSelfRef.cla__DOT__gp1_loop__BRA__7__KET____DOT__gp_inst__DOT__a));
    bufp->fullBit(oldp+134,(vlSelfRef.cla__DOT__gp1_loop__BRA__7__KET____DOT__gp_inst__DOT__b));
    bufp->fullBit(oldp+135,(vlSelfRef.cla__DOT__gp1_loop__BRA__7__KET____DOT__gp_inst__DOT__g));
    bufp->fullBit(oldp+136,(vlSelfRef.cla__DOT__gp1_loop__BRA__7__KET____DOT__gp_inst__DOT__p));
    bufp->fullBit(oldp+137,(vlSelfRef.cla__DOT__gp1_loop__BRA__8__KET____DOT__gp_inst__DOT__a));
    bufp->fullBit(oldp+138,(vlSelfRef.cla__DOT__gp1_loop__BRA__8__KET____DOT__gp_inst__DOT__b));
    bufp->fullBit(oldp+139,(vlSelfRef.cla__DOT__gp1_loop__BRA__8__KET____DOT__gp_inst__DOT__g));
    bufp->fullBit(oldp+140,(vlSelfRef.cla__DOT__gp1_loop__BRA__8__KET____DOT__gp_inst__DOT__p));
    bufp->fullBit(oldp+141,(vlSelfRef.cla__DOT__gp1_loop__BRA__9__KET____DOT__gp_inst__DOT__a));
    bufp->fullBit(oldp+142,(vlSelfRef.cla__DOT__gp1_loop__BRA__9__KET____DOT__gp_inst__DOT__b));
    bufp->fullBit(oldp+143,(vlSelfRef.cla__DOT__gp1_loop__BRA__9__KET____DOT__gp_inst__DOT__g));
    bufp->fullBit(oldp+144,(vlSelfRef.cla__DOT__gp1_loop__BRA__9__KET____DOT__gp_inst__DOT__p));
    bufp->fullCData(oldp+145,(vlSelfRef.cla__DOT__gp8_high__DOT__gin),8);
    bufp->fullCData(oldp+146,(vlSelfRef.cla__DOT__gp8_high__DOT__pin),8);
    bufp->fullBit(oldp+147,(vlSelfRef.cla__DOT__gp8_high__DOT__cin));
    bufp->fullBit(oldp+148,(vlSelfRef.cla__DOT__gp8_high__DOT__gout));
    bufp->fullBit(oldp+149,(vlSelfRef.cla__DOT__gp8_high__DOT__pout));
    bufp->fullCData(oldp+150,(vlSelfRef.cla__DOT__gp8_high__DOT__cout),7);
    bufp->fullBit(oldp+151,(vlSelfRef.cla__DOT__gp8_high__DOT__g_lower));
    bufp->fullBit(oldp+152,(vlSelfRef.cla__DOT__gp8_high__DOT__p_lower));
    bufp->fullBit(oldp+153,(vlSelfRef.cla__DOT__gp8_high__DOT__g_upper));
    bufp->fullBit(oldp+154,(vlSelfRef.cla__DOT__gp8_high__DOT__p_upper));
    bufp->fullBit(oldp+155,(vlSelfRef.cla__DOT__gp8_high__DOT__c_mid));
    bufp->fullCData(oldp+156,(vlSelfRef.cla__DOT__gp8_high__DOT__gp_segment_high__DOT__gin),4);
    bufp->fullCData(oldp+157,(vlSelfRef.cla__DOT__gp8_high__DOT__gp_segment_high__DOT__pin),4);
    bufp->fullBit(oldp+158,(vlSelfRef.cla__DOT__gp8_high__DOT__gp_segment_high__DOT__cin));
    bufp->fullBit(oldp+159,(vlSelfRef.cla__DOT__gp8_high__DOT__gp_segment_high__DOT__gout));
    bufp->fullBit(oldp+160,(vlSelfRef.cla__DOT__gp8_high__DOT__gp_segment_high__DOT__pout));
    bufp->fullCData(oldp+161,(vlSelfRef.cla__DOT__gp8_high__DOT__gp_segment_high__DOT__cout),3);
    bufp->fullCData(oldp+162,(vlSelfRef.cla__DOT__gp8_high__DOT__gp_segment_low__DOT__gin),4);
    bufp->fullCData(oldp+163,(vlSelfRef.cla__DOT__gp8_high__DOT__gp_segment_low__DOT__pin),4);
    bufp->fullBit(oldp+164,(vlSelfRef.cla__DOT__gp8_high__DOT__gp_segment_low__DOT__cin));
    bufp->fullBit(oldp+165,(vlSelfRef.cla__DOT__gp8_high__DOT__gp_segment_low__DOT__gout));
    bufp->fullBit(oldp+166,(vlSelfRef.cla__DOT__gp8_high__DOT__gp_segment_low__DOT__pout));
    bufp->fullCData(oldp+167,(vlSelfRef.cla__DOT__gp8_high__DOT__gp_segment_low__DOT__cout),3);
    bufp->fullCData(oldp+168,(vlSelfRef.cla__DOT__gp8_low__DOT__gin),8);
    bufp->fullCData(oldp+169,(vlSelfRef.cla__DOT__gp8_low__DOT__pin),8);
    bufp->fullBit(oldp+170,(vlSelfRef.cla__DOT__gp8_low__DOT__cin));
    bufp->fullBit(oldp+171,(vlSelfRef.cla__DOT__gp8_low__DOT__gout));
    bufp->fullBit(oldp+172,(vlSelfRef.cla__DOT__gp8_low__DOT__pout));
    bufp->fullCData(oldp+173,(vlSelfRef.cla__DOT__gp8_low__DOT__cout),7);
    bufp->fullBit(oldp+174,(vlSelfRef.cla__DOT__gp8_low__DOT__g_lower));
    bufp->fullBit(oldp+175,(vlSelfRef.cla__DOT__gp8_low__DOT__p_lower));
    bufp->fullBit(oldp+176,(vlSelfRef.cla__DOT__gp8_low__DOT__g_upper));
    bufp->fullBit(oldp+177,(vlSelfRef.cla__DOT__gp8_low__DOT__p_upper));
    bufp->fullBit(oldp+178,(vlSelfRef.cla__DOT__gp8_low__DOT__c_mid));
    bufp->fullCData(oldp+179,(vlSelfRef.cla__DOT__gp8_low__DOT__gp_segment_high__DOT__gin),4);
    bufp->fullCData(oldp+180,(vlSelfRef.cla__DOT__gp8_low__DOT__gp_segment_high__DOT__pin),4);
    bufp->fullBit(oldp+181,(vlSelfRef.cla__DOT__gp8_low__DOT__gp_segment_high__DOT__cin));
    bufp->fullBit(oldp+182,(vlSelfRef.cla__DOT__gp8_low__DOT__gp_segment_high__DOT__gout));
    bufp->fullBit(oldp+183,(vlSelfRef.cla__DOT__gp8_low__DOT__gp_segment_high__DOT__pout));
    bufp->fullCData(oldp+184,(vlSelfRef.cla__DOT__gp8_low__DOT__gp_segment_high__DOT__cout),3);
    bufp->fullCData(oldp+185,(vlSelfRef.cla__DOT__gp8_low__DOT__gp_segment_low__DOT__gin),4);
    bufp->fullCData(oldp+186,(vlSelfRef.cla__DOT__gp8_low__DOT__gp_segment_low__DOT__pin),4);
    bufp->fullBit(oldp+187,(vlSelfRef.cla__DOT__gp8_low__DOT__gp_segment_low__DOT__cin));
    bufp->fullBit(oldp+188,(vlSelfRef.cla__DOT__gp8_low__DOT__gp_segment_low__DOT__gout));
    bufp->fullBit(oldp+189,(vlSelfRef.cla__DOT__gp8_low__DOT__gp_segment_low__DOT__pout));
    bufp->fullCData(oldp+190,(vlSelfRef.cla__DOT__gp8_low__DOT__gp_segment_low__DOT__cout),3);
    bufp->fullCData(oldp+191,(vlSelfRef.cla__DOT__gp8_mid1__DOT__gin),8);
    bufp->fullCData(oldp+192,(vlSelfRef.cla__DOT__gp8_mid1__DOT__pin),8);
    bufp->fullBit(oldp+193,(vlSelfRef.cla__DOT__gp8_mid1__DOT__cin));
    bufp->fullBit(oldp+194,(vlSelfRef.cla__DOT__gp8_mid1__DOT__gout));
    bufp->fullBit(oldp+195,(vlSelfRef.cla__DOT__gp8_mid1__DOT__pout));
    bufp->fullCData(oldp+196,(vlSelfRef.cla__DOT__gp8_mid1__DOT__cout),7);
    bufp->fullBit(oldp+197,(vlSelfRef.cla__DOT__gp8_mid1__DOT__g_lower));
    bufp->fullBit(oldp+198,(vlSelfRef.cla__DOT__gp8_mid1__DOT__p_lower));
    bufp->fullBit(oldp+199,(vlSelfRef.cla__DOT__gp8_mid1__DOT__g_upper));
    bufp->fullBit(oldp+200,(vlSelfRef.cla__DOT__gp8_mid1__DOT__p_upper));
    bufp->fullBit(oldp+201,(vlSelfRef.cla__DOT__gp8_mid1__DOT__c_mid));
    bufp->fullCData(oldp+202,(vlSelfRef.cla__DOT__gp8_mid1__DOT__gp_segment_high__DOT__gin),4);
    bufp->fullCData(oldp+203,(vlSelfRef.cla__DOT__gp8_mid1__DOT__gp_segment_high__DOT__pin),4);
    bufp->fullBit(oldp+204,(vlSelfRef.cla__DOT__gp8_mid1__DOT__gp_segment_high__DOT__cin));
    bufp->fullBit(oldp+205,(vlSelfRef.cla__DOT__gp8_mid1__DOT__gp_segment_high__DOT__gout));
    bufp->fullBit(oldp+206,(vlSelfRef.cla__DOT__gp8_mid1__DOT__gp_segment_high__DOT__pout));
    bufp->fullCData(oldp+207,(vlSelfRef.cla__DOT__gp8_mid1__DOT__gp_segment_high__DOT__cout),3);
    bufp->fullCData(oldp+208,(vlSelfRef.cla__DOT__gp8_mid1__DOT__gp_segment_low__DOT__gin),4);
    bufp->fullCData(oldp+209,(vlSelfRef.cla__DOT__gp8_mid1__DOT__gp_segment_low__DOT__pin),4);
    bufp->fullBit(oldp+210,(vlSelfRef.cla__DOT__gp8_mid1__DOT__gp_segment_low__DOT__cin));
    bufp->fullBit(oldp+211,(vlSelfRef.cla__DOT__gp8_mid1__DOT__gp_segment_low__DOT__gout));
    bufp->fullBit(oldp+212,(vlSelfRef.cla__DOT__gp8_mid1__DOT__gp_segment_low__DOT__pout));
    bufp->fullCData(oldp+213,(vlSelfRef.cla__DOT__gp8_mid1__DOT__gp_segment_low__DOT__cout),3);
    bufp->fullCData(oldp+214,(vlSelfRef.cla__DOT__gp8_mid2__DOT__gin),8);
    bufp->fullCData(oldp+215,(vlSelfRef.cla__DOT__gp8_mid2__DOT__pin),8);
    bufp->fullBit(oldp+216,(vlSelfRef.cla__DOT__gp8_mid2__DOT__cin));
    bufp->fullBit(oldp+217,(vlSelfRef.cla__DOT__gp8_mid2__DOT__gout));
    bufp->fullBit(oldp+218,(vlSelfRef.cla__DOT__gp8_mid2__DOT__pout));
    bufp->fullCData(oldp+219,(vlSelfRef.cla__DOT__gp8_mid2__DOT__cout),7);
    bufp->fullBit(oldp+220,(vlSelfRef.cla__DOT__gp8_mid2__DOT__g_lower));
    bufp->fullBit(oldp+221,(vlSelfRef.cla__DOT__gp8_mid2__DOT__p_lower));
    bufp->fullBit(oldp+222,(vlSelfRef.cla__DOT__gp8_mid2__DOT__g_upper));
    bufp->fullBit(oldp+223,(vlSelfRef.cla__DOT__gp8_mid2__DOT__p_upper));
    bufp->fullBit(oldp+224,(vlSelfRef.cla__DOT__gp8_mid2__DOT__c_mid));
    bufp->fullCData(oldp+225,(vlSelfRef.cla__DOT__gp8_mid2__DOT__gp_segment_high__DOT__gin),4);
    bufp->fullCData(oldp+226,(vlSelfRef.cla__DOT__gp8_mid2__DOT__gp_segment_high__DOT__pin),4);
    bufp->fullBit(oldp+227,(vlSelfRef.cla__DOT__gp8_mid2__DOT__gp_segment_high__DOT__cin));
    bufp->fullBit(oldp+228,(vlSelfRef.cla__DOT__gp8_mid2__DOT__gp_segment_high__DOT__gout));
    bufp->fullBit(oldp+229,(vlSelfRef.cla__DOT__gp8_mid2__DOT__gp_segment_high__DOT__pout));
    bufp->fullCData(oldp+230,(vlSelfRef.cla__DOT__gp8_mid2__DOT__gp_segment_high__DOT__cout),3);
    bufp->fullCData(oldp+231,(vlSelfRef.cla__DOT__gp8_mid2__DOT__gp_segment_low__DOT__gin),4);
    bufp->fullCData(oldp+232,(vlSelfRef.cla__DOT__gp8_mid2__DOT__gp_segment_low__DOT__pin),4);
    bufp->fullBit(oldp+233,(vlSelfRef.cla__DOT__gp8_mid2__DOT__gp_segment_low__DOT__cin));
    bufp->fullBit(oldp+234,(vlSelfRef.cla__DOT__gp8_mid2__DOT__gp_segment_low__DOT__gout));
    bufp->fullBit(oldp+235,(vlSelfRef.cla__DOT__gp8_mid2__DOT__gp_segment_low__DOT__pout));
    bufp->fullCData(oldp+236,(vlSelfRef.cla__DOT__gp8_mid2__DOT__gp_segment_low__DOT__cout),3);
}
