// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_fst_c.h"
#include "Vtop__Syms.h"


void Vtop___024root__trace_chg_0_sub_0(Vtop___024root* vlSelf, VerilatedFst::Buffer* bufp);

void Vtop___024root__trace_chg_0(void* voidSelf, VerilatedFst::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_chg_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    if (VL_UNLIKELY(!vlSymsp->__Vm_activity)) return;
    // Body
    Vtop___024root__trace_chg_0_sub_0((&vlSymsp->TOP), bufp);
}

void Vtop___024root__trace_chg_0_sub_0(Vtop___024root* vlSelf, VerilatedFst::Buffer* bufp) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_chg_0_sub_0\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode + 1);
    // Body
    bufp->chgIData(oldp+0,(vlSelfRef.a),32);
    bufp->chgIData(oldp+1,(vlSelfRef.b),32);
    bufp->chgBit(oldp+2,(vlSelfRef.cin));
    bufp->chgIData(oldp+3,(vlSelfRef.sum),32);
    bufp->chgIData(oldp+4,(vlSelfRef.cla__DOT__a),32);
    bufp->chgIData(oldp+5,(vlSelfRef.cla__DOT__b),32);
    bufp->chgBit(oldp+6,(vlSelfRef.cla__DOT__cin));
    bufp->chgIData(oldp+7,(vlSelfRef.cla__DOT__sum),32);
    bufp->chgIData(oldp+8,(vlSelfRef.cla__DOT__g),32);
    bufp->chgIData(oldp+9,(vlSelfRef.cla__DOT__p),32);
    bufp->chgIData(oldp+10,(vlSelfRef.cla__DOT__carry),32);
    bufp->chgCData(oldp+11,(vlSelfRef.cla__DOT__gout),4);
    bufp->chgCData(oldp+12,(vlSelfRef.cla__DOT__pout),4);
    bufp->chgBit(oldp+13,(vlSelfRef.cla__DOT__c8));
    bufp->chgBit(oldp+14,(vlSelfRef.cla__DOT__c16));
    bufp->chgBit(oldp+15,(vlSelfRef.cla__DOT__c24));
    bufp->chgBit(oldp+16,(vlSelfRef.cla__DOT__gp1_loop__BRA__0__KET____DOT__gp_inst__DOT__a));
    bufp->chgBit(oldp+17,(vlSelfRef.cla__DOT__gp1_loop__BRA__0__KET____DOT__gp_inst__DOT__b));
    bufp->chgBit(oldp+18,(vlSelfRef.cla__DOT__gp1_loop__BRA__0__KET____DOT__gp_inst__DOT__g));
    bufp->chgBit(oldp+19,(vlSelfRef.cla__DOT__gp1_loop__BRA__0__KET____DOT__gp_inst__DOT__p));
    bufp->chgBit(oldp+20,(vlSelfRef.cla__DOT__gp1_loop__BRA__10__KET____DOT__gp_inst__DOT__a));
    bufp->chgBit(oldp+21,(vlSelfRef.cla__DOT__gp1_loop__BRA__10__KET____DOT__gp_inst__DOT__b));
    bufp->chgBit(oldp+22,(vlSelfRef.cla__DOT__gp1_loop__BRA__10__KET____DOT__gp_inst__DOT__g));
    bufp->chgBit(oldp+23,(vlSelfRef.cla__DOT__gp1_loop__BRA__10__KET____DOT__gp_inst__DOT__p));
    bufp->chgBit(oldp+24,(vlSelfRef.cla__DOT__gp1_loop__BRA__11__KET____DOT__gp_inst__DOT__a));
    bufp->chgBit(oldp+25,(vlSelfRef.cla__DOT__gp1_loop__BRA__11__KET____DOT__gp_inst__DOT__b));
    bufp->chgBit(oldp+26,(vlSelfRef.cla__DOT__gp1_loop__BRA__11__KET____DOT__gp_inst__DOT__g));
    bufp->chgBit(oldp+27,(vlSelfRef.cla__DOT__gp1_loop__BRA__11__KET____DOT__gp_inst__DOT__p));
    bufp->chgBit(oldp+28,(vlSelfRef.cla__DOT__gp1_loop__BRA__12__KET____DOT__gp_inst__DOT__a));
    bufp->chgBit(oldp+29,(vlSelfRef.cla__DOT__gp1_loop__BRA__12__KET____DOT__gp_inst__DOT__b));
    bufp->chgBit(oldp+30,(vlSelfRef.cla__DOT__gp1_loop__BRA__12__KET____DOT__gp_inst__DOT__g));
    bufp->chgBit(oldp+31,(vlSelfRef.cla__DOT__gp1_loop__BRA__12__KET____DOT__gp_inst__DOT__p));
    bufp->chgBit(oldp+32,(vlSelfRef.cla__DOT__gp1_loop__BRA__13__KET____DOT__gp_inst__DOT__a));
    bufp->chgBit(oldp+33,(vlSelfRef.cla__DOT__gp1_loop__BRA__13__KET____DOT__gp_inst__DOT__b));
    bufp->chgBit(oldp+34,(vlSelfRef.cla__DOT__gp1_loop__BRA__13__KET____DOT__gp_inst__DOT__g));
    bufp->chgBit(oldp+35,(vlSelfRef.cla__DOT__gp1_loop__BRA__13__KET____DOT__gp_inst__DOT__p));
    bufp->chgBit(oldp+36,(vlSelfRef.cla__DOT__gp1_loop__BRA__14__KET____DOT__gp_inst__DOT__a));
    bufp->chgBit(oldp+37,(vlSelfRef.cla__DOT__gp1_loop__BRA__14__KET____DOT__gp_inst__DOT__b));
    bufp->chgBit(oldp+38,(vlSelfRef.cla__DOT__gp1_loop__BRA__14__KET____DOT__gp_inst__DOT__g));
    bufp->chgBit(oldp+39,(vlSelfRef.cla__DOT__gp1_loop__BRA__14__KET____DOT__gp_inst__DOT__p));
    bufp->chgBit(oldp+40,(vlSelfRef.cla__DOT__gp1_loop__BRA__15__KET____DOT__gp_inst__DOT__a));
    bufp->chgBit(oldp+41,(vlSelfRef.cla__DOT__gp1_loop__BRA__15__KET____DOT__gp_inst__DOT__b));
    bufp->chgBit(oldp+42,(vlSelfRef.cla__DOT__gp1_loop__BRA__15__KET____DOT__gp_inst__DOT__g));
    bufp->chgBit(oldp+43,(vlSelfRef.cla__DOT__gp1_loop__BRA__15__KET____DOT__gp_inst__DOT__p));
    bufp->chgBit(oldp+44,(vlSelfRef.cla__DOT__gp1_loop__BRA__16__KET____DOT__gp_inst__DOT__a));
    bufp->chgBit(oldp+45,(vlSelfRef.cla__DOT__gp1_loop__BRA__16__KET____DOT__gp_inst__DOT__b));
    bufp->chgBit(oldp+46,(vlSelfRef.cla__DOT__gp1_loop__BRA__16__KET____DOT__gp_inst__DOT__g));
    bufp->chgBit(oldp+47,(vlSelfRef.cla__DOT__gp1_loop__BRA__16__KET____DOT__gp_inst__DOT__p));
    bufp->chgBit(oldp+48,(vlSelfRef.cla__DOT__gp1_loop__BRA__17__KET____DOT__gp_inst__DOT__a));
    bufp->chgBit(oldp+49,(vlSelfRef.cla__DOT__gp1_loop__BRA__17__KET____DOT__gp_inst__DOT__b));
    bufp->chgBit(oldp+50,(vlSelfRef.cla__DOT__gp1_loop__BRA__17__KET____DOT__gp_inst__DOT__g));
    bufp->chgBit(oldp+51,(vlSelfRef.cla__DOT__gp1_loop__BRA__17__KET____DOT__gp_inst__DOT__p));
    bufp->chgBit(oldp+52,(vlSelfRef.cla__DOT__gp1_loop__BRA__18__KET____DOT__gp_inst__DOT__a));
    bufp->chgBit(oldp+53,(vlSelfRef.cla__DOT__gp1_loop__BRA__18__KET____DOT__gp_inst__DOT__b));
    bufp->chgBit(oldp+54,(vlSelfRef.cla__DOT__gp1_loop__BRA__18__KET____DOT__gp_inst__DOT__g));
    bufp->chgBit(oldp+55,(vlSelfRef.cla__DOT__gp1_loop__BRA__18__KET____DOT__gp_inst__DOT__p));
    bufp->chgBit(oldp+56,(vlSelfRef.cla__DOT__gp1_loop__BRA__19__KET____DOT__gp_inst__DOT__a));
    bufp->chgBit(oldp+57,(vlSelfRef.cla__DOT__gp1_loop__BRA__19__KET____DOT__gp_inst__DOT__b));
    bufp->chgBit(oldp+58,(vlSelfRef.cla__DOT__gp1_loop__BRA__19__KET____DOT__gp_inst__DOT__g));
    bufp->chgBit(oldp+59,(vlSelfRef.cla__DOT__gp1_loop__BRA__19__KET____DOT__gp_inst__DOT__p));
    bufp->chgBit(oldp+60,(vlSelfRef.cla__DOT__gp1_loop__BRA__1__KET____DOT__gp_inst__DOT__a));
    bufp->chgBit(oldp+61,(vlSelfRef.cla__DOT__gp1_loop__BRA__1__KET____DOT__gp_inst__DOT__b));
    bufp->chgBit(oldp+62,(vlSelfRef.cla__DOT__gp1_loop__BRA__1__KET____DOT__gp_inst__DOT__g));
    bufp->chgBit(oldp+63,(vlSelfRef.cla__DOT__gp1_loop__BRA__1__KET____DOT__gp_inst__DOT__p));
    bufp->chgBit(oldp+64,(vlSelfRef.cla__DOT__gp1_loop__BRA__20__KET____DOT__gp_inst__DOT__a));
    bufp->chgBit(oldp+65,(vlSelfRef.cla__DOT__gp1_loop__BRA__20__KET____DOT__gp_inst__DOT__b));
    bufp->chgBit(oldp+66,(vlSelfRef.cla__DOT__gp1_loop__BRA__20__KET____DOT__gp_inst__DOT__g));
    bufp->chgBit(oldp+67,(vlSelfRef.cla__DOT__gp1_loop__BRA__20__KET____DOT__gp_inst__DOT__p));
    bufp->chgBit(oldp+68,(vlSelfRef.cla__DOT__gp1_loop__BRA__21__KET____DOT__gp_inst__DOT__a));
    bufp->chgBit(oldp+69,(vlSelfRef.cla__DOT__gp1_loop__BRA__21__KET____DOT__gp_inst__DOT__b));
    bufp->chgBit(oldp+70,(vlSelfRef.cla__DOT__gp1_loop__BRA__21__KET____DOT__gp_inst__DOT__g));
    bufp->chgBit(oldp+71,(vlSelfRef.cla__DOT__gp1_loop__BRA__21__KET____DOT__gp_inst__DOT__p));
    bufp->chgBit(oldp+72,(vlSelfRef.cla__DOT__gp1_loop__BRA__22__KET____DOT__gp_inst__DOT__a));
    bufp->chgBit(oldp+73,(vlSelfRef.cla__DOT__gp1_loop__BRA__22__KET____DOT__gp_inst__DOT__b));
    bufp->chgBit(oldp+74,(vlSelfRef.cla__DOT__gp1_loop__BRA__22__KET____DOT__gp_inst__DOT__g));
    bufp->chgBit(oldp+75,(vlSelfRef.cla__DOT__gp1_loop__BRA__22__KET____DOT__gp_inst__DOT__p));
    bufp->chgBit(oldp+76,(vlSelfRef.cla__DOT__gp1_loop__BRA__23__KET____DOT__gp_inst__DOT__a));
    bufp->chgBit(oldp+77,(vlSelfRef.cla__DOT__gp1_loop__BRA__23__KET____DOT__gp_inst__DOT__b));
    bufp->chgBit(oldp+78,(vlSelfRef.cla__DOT__gp1_loop__BRA__23__KET____DOT__gp_inst__DOT__g));
    bufp->chgBit(oldp+79,(vlSelfRef.cla__DOT__gp1_loop__BRA__23__KET____DOT__gp_inst__DOT__p));
    bufp->chgBit(oldp+80,(vlSelfRef.cla__DOT__gp1_loop__BRA__24__KET____DOT__gp_inst__DOT__a));
    bufp->chgBit(oldp+81,(vlSelfRef.cla__DOT__gp1_loop__BRA__24__KET____DOT__gp_inst__DOT__b));
    bufp->chgBit(oldp+82,(vlSelfRef.cla__DOT__gp1_loop__BRA__24__KET____DOT__gp_inst__DOT__g));
    bufp->chgBit(oldp+83,(vlSelfRef.cla__DOT__gp1_loop__BRA__24__KET____DOT__gp_inst__DOT__p));
    bufp->chgBit(oldp+84,(vlSelfRef.cla__DOT__gp1_loop__BRA__25__KET____DOT__gp_inst__DOT__a));
    bufp->chgBit(oldp+85,(vlSelfRef.cla__DOT__gp1_loop__BRA__25__KET____DOT__gp_inst__DOT__b));
    bufp->chgBit(oldp+86,(vlSelfRef.cla__DOT__gp1_loop__BRA__25__KET____DOT__gp_inst__DOT__g));
    bufp->chgBit(oldp+87,(vlSelfRef.cla__DOT__gp1_loop__BRA__25__KET____DOT__gp_inst__DOT__p));
    bufp->chgBit(oldp+88,(vlSelfRef.cla__DOT__gp1_loop__BRA__26__KET____DOT__gp_inst__DOT__a));
    bufp->chgBit(oldp+89,(vlSelfRef.cla__DOT__gp1_loop__BRA__26__KET____DOT__gp_inst__DOT__b));
    bufp->chgBit(oldp+90,(vlSelfRef.cla__DOT__gp1_loop__BRA__26__KET____DOT__gp_inst__DOT__g));
    bufp->chgBit(oldp+91,(vlSelfRef.cla__DOT__gp1_loop__BRA__26__KET____DOT__gp_inst__DOT__p));
    bufp->chgBit(oldp+92,(vlSelfRef.cla__DOT__gp1_loop__BRA__27__KET____DOT__gp_inst__DOT__a));
    bufp->chgBit(oldp+93,(vlSelfRef.cla__DOT__gp1_loop__BRA__27__KET____DOT__gp_inst__DOT__b));
    bufp->chgBit(oldp+94,(vlSelfRef.cla__DOT__gp1_loop__BRA__27__KET____DOT__gp_inst__DOT__g));
    bufp->chgBit(oldp+95,(vlSelfRef.cla__DOT__gp1_loop__BRA__27__KET____DOT__gp_inst__DOT__p));
    bufp->chgBit(oldp+96,(vlSelfRef.cla__DOT__gp1_loop__BRA__28__KET____DOT__gp_inst__DOT__a));
    bufp->chgBit(oldp+97,(vlSelfRef.cla__DOT__gp1_loop__BRA__28__KET____DOT__gp_inst__DOT__b));
    bufp->chgBit(oldp+98,(vlSelfRef.cla__DOT__gp1_loop__BRA__28__KET____DOT__gp_inst__DOT__g));
    bufp->chgBit(oldp+99,(vlSelfRef.cla__DOT__gp1_loop__BRA__28__KET____DOT__gp_inst__DOT__p));
    bufp->chgBit(oldp+100,(vlSelfRef.cla__DOT__gp1_loop__BRA__29__KET____DOT__gp_inst__DOT__a));
    bufp->chgBit(oldp+101,(vlSelfRef.cla__DOT__gp1_loop__BRA__29__KET____DOT__gp_inst__DOT__b));
    bufp->chgBit(oldp+102,(vlSelfRef.cla__DOT__gp1_loop__BRA__29__KET____DOT__gp_inst__DOT__g));
    bufp->chgBit(oldp+103,(vlSelfRef.cla__DOT__gp1_loop__BRA__29__KET____DOT__gp_inst__DOT__p));
    bufp->chgBit(oldp+104,(vlSelfRef.cla__DOT__gp1_loop__BRA__2__KET____DOT__gp_inst__DOT__a));
    bufp->chgBit(oldp+105,(vlSelfRef.cla__DOT__gp1_loop__BRA__2__KET____DOT__gp_inst__DOT__b));
    bufp->chgBit(oldp+106,(vlSelfRef.cla__DOT__gp1_loop__BRA__2__KET____DOT__gp_inst__DOT__g));
    bufp->chgBit(oldp+107,(vlSelfRef.cla__DOT__gp1_loop__BRA__2__KET____DOT__gp_inst__DOT__p));
    bufp->chgBit(oldp+108,(vlSelfRef.cla__DOT__gp1_loop__BRA__30__KET____DOT__gp_inst__DOT__a));
    bufp->chgBit(oldp+109,(vlSelfRef.cla__DOT__gp1_loop__BRA__30__KET____DOT__gp_inst__DOT__b));
    bufp->chgBit(oldp+110,(vlSelfRef.cla__DOT__gp1_loop__BRA__30__KET____DOT__gp_inst__DOT__g));
    bufp->chgBit(oldp+111,(vlSelfRef.cla__DOT__gp1_loop__BRA__30__KET____DOT__gp_inst__DOT__p));
    bufp->chgBit(oldp+112,(vlSelfRef.cla__DOT__gp1_loop__BRA__31__KET____DOT__gp_inst__DOT__a));
    bufp->chgBit(oldp+113,(vlSelfRef.cla__DOT__gp1_loop__BRA__31__KET____DOT__gp_inst__DOT__b));
    bufp->chgBit(oldp+114,(vlSelfRef.cla__DOT__gp1_loop__BRA__31__KET____DOT__gp_inst__DOT__g));
    bufp->chgBit(oldp+115,(vlSelfRef.cla__DOT__gp1_loop__BRA__31__KET____DOT__gp_inst__DOT__p));
    bufp->chgBit(oldp+116,(vlSelfRef.cla__DOT__gp1_loop__BRA__3__KET____DOT__gp_inst__DOT__a));
    bufp->chgBit(oldp+117,(vlSelfRef.cla__DOT__gp1_loop__BRA__3__KET____DOT__gp_inst__DOT__b));
    bufp->chgBit(oldp+118,(vlSelfRef.cla__DOT__gp1_loop__BRA__3__KET____DOT__gp_inst__DOT__g));
    bufp->chgBit(oldp+119,(vlSelfRef.cla__DOT__gp1_loop__BRA__3__KET____DOT__gp_inst__DOT__p));
    bufp->chgBit(oldp+120,(vlSelfRef.cla__DOT__gp1_loop__BRA__4__KET____DOT__gp_inst__DOT__a));
    bufp->chgBit(oldp+121,(vlSelfRef.cla__DOT__gp1_loop__BRA__4__KET____DOT__gp_inst__DOT__b));
    bufp->chgBit(oldp+122,(vlSelfRef.cla__DOT__gp1_loop__BRA__4__KET____DOT__gp_inst__DOT__g));
    bufp->chgBit(oldp+123,(vlSelfRef.cla__DOT__gp1_loop__BRA__4__KET____DOT__gp_inst__DOT__p));
    bufp->chgBit(oldp+124,(vlSelfRef.cla__DOT__gp1_loop__BRA__5__KET____DOT__gp_inst__DOT__a));
    bufp->chgBit(oldp+125,(vlSelfRef.cla__DOT__gp1_loop__BRA__5__KET____DOT__gp_inst__DOT__b));
    bufp->chgBit(oldp+126,(vlSelfRef.cla__DOT__gp1_loop__BRA__5__KET____DOT__gp_inst__DOT__g));
    bufp->chgBit(oldp+127,(vlSelfRef.cla__DOT__gp1_loop__BRA__5__KET____DOT__gp_inst__DOT__p));
    bufp->chgBit(oldp+128,(vlSelfRef.cla__DOT__gp1_loop__BRA__6__KET____DOT__gp_inst__DOT__a));
    bufp->chgBit(oldp+129,(vlSelfRef.cla__DOT__gp1_loop__BRA__6__KET____DOT__gp_inst__DOT__b));
    bufp->chgBit(oldp+130,(vlSelfRef.cla__DOT__gp1_loop__BRA__6__KET____DOT__gp_inst__DOT__g));
    bufp->chgBit(oldp+131,(vlSelfRef.cla__DOT__gp1_loop__BRA__6__KET____DOT__gp_inst__DOT__p));
    bufp->chgBit(oldp+132,(vlSelfRef.cla__DOT__gp1_loop__BRA__7__KET____DOT__gp_inst__DOT__a));
    bufp->chgBit(oldp+133,(vlSelfRef.cla__DOT__gp1_loop__BRA__7__KET____DOT__gp_inst__DOT__b));
    bufp->chgBit(oldp+134,(vlSelfRef.cla__DOT__gp1_loop__BRA__7__KET____DOT__gp_inst__DOT__g));
    bufp->chgBit(oldp+135,(vlSelfRef.cla__DOT__gp1_loop__BRA__7__KET____DOT__gp_inst__DOT__p));
    bufp->chgBit(oldp+136,(vlSelfRef.cla__DOT__gp1_loop__BRA__8__KET____DOT__gp_inst__DOT__a));
    bufp->chgBit(oldp+137,(vlSelfRef.cla__DOT__gp1_loop__BRA__8__KET____DOT__gp_inst__DOT__b));
    bufp->chgBit(oldp+138,(vlSelfRef.cla__DOT__gp1_loop__BRA__8__KET____DOT__gp_inst__DOT__g));
    bufp->chgBit(oldp+139,(vlSelfRef.cla__DOT__gp1_loop__BRA__8__KET____DOT__gp_inst__DOT__p));
    bufp->chgBit(oldp+140,(vlSelfRef.cla__DOT__gp1_loop__BRA__9__KET____DOT__gp_inst__DOT__a));
    bufp->chgBit(oldp+141,(vlSelfRef.cla__DOT__gp1_loop__BRA__9__KET____DOT__gp_inst__DOT__b));
    bufp->chgBit(oldp+142,(vlSelfRef.cla__DOT__gp1_loop__BRA__9__KET____DOT__gp_inst__DOT__g));
    bufp->chgBit(oldp+143,(vlSelfRef.cla__DOT__gp1_loop__BRA__9__KET____DOT__gp_inst__DOT__p));
    bufp->chgCData(oldp+144,(vlSelfRef.cla__DOT__gp8_high__DOT__gin),8);
    bufp->chgCData(oldp+145,(vlSelfRef.cla__DOT__gp8_high__DOT__pin),8);
    bufp->chgBit(oldp+146,(vlSelfRef.cla__DOT__gp8_high__DOT__cin));
    bufp->chgBit(oldp+147,(vlSelfRef.cla__DOT__gp8_high__DOT__gout));
    bufp->chgBit(oldp+148,(vlSelfRef.cla__DOT__gp8_high__DOT__pout));
    bufp->chgCData(oldp+149,(vlSelfRef.cla__DOT__gp8_high__DOT__cout),7);
    bufp->chgBit(oldp+150,(vlSelfRef.cla__DOT__gp8_high__DOT__g_lower));
    bufp->chgBit(oldp+151,(vlSelfRef.cla__DOT__gp8_high__DOT__p_lower));
    bufp->chgBit(oldp+152,(vlSelfRef.cla__DOT__gp8_high__DOT__g_upper));
    bufp->chgBit(oldp+153,(vlSelfRef.cla__DOT__gp8_high__DOT__p_upper));
    bufp->chgBit(oldp+154,(vlSelfRef.cla__DOT__gp8_high__DOT__c_mid));
    bufp->chgCData(oldp+155,(vlSelfRef.cla__DOT__gp8_high__DOT__gp_segment_high__DOT__gin),4);
    bufp->chgCData(oldp+156,(vlSelfRef.cla__DOT__gp8_high__DOT__gp_segment_high__DOT__pin),4);
    bufp->chgBit(oldp+157,(vlSelfRef.cla__DOT__gp8_high__DOT__gp_segment_high__DOT__cin));
    bufp->chgBit(oldp+158,(vlSelfRef.cla__DOT__gp8_high__DOT__gp_segment_high__DOT__gout));
    bufp->chgBit(oldp+159,(vlSelfRef.cla__DOT__gp8_high__DOT__gp_segment_high__DOT__pout));
    bufp->chgCData(oldp+160,(vlSelfRef.cla__DOT__gp8_high__DOT__gp_segment_high__DOT__cout),3);
    bufp->chgCData(oldp+161,(vlSelfRef.cla__DOT__gp8_high__DOT__gp_segment_low__DOT__gin),4);
    bufp->chgCData(oldp+162,(vlSelfRef.cla__DOT__gp8_high__DOT__gp_segment_low__DOT__pin),4);
    bufp->chgBit(oldp+163,(vlSelfRef.cla__DOT__gp8_high__DOT__gp_segment_low__DOT__cin));
    bufp->chgBit(oldp+164,(vlSelfRef.cla__DOT__gp8_high__DOT__gp_segment_low__DOT__gout));
    bufp->chgBit(oldp+165,(vlSelfRef.cla__DOT__gp8_high__DOT__gp_segment_low__DOT__pout));
    bufp->chgCData(oldp+166,(vlSelfRef.cla__DOT__gp8_high__DOT__gp_segment_low__DOT__cout),3);
    bufp->chgCData(oldp+167,(vlSelfRef.cla__DOT__gp8_low__DOT__gin),8);
    bufp->chgCData(oldp+168,(vlSelfRef.cla__DOT__gp8_low__DOT__pin),8);
    bufp->chgBit(oldp+169,(vlSelfRef.cla__DOT__gp8_low__DOT__cin));
    bufp->chgBit(oldp+170,(vlSelfRef.cla__DOT__gp8_low__DOT__gout));
    bufp->chgBit(oldp+171,(vlSelfRef.cla__DOT__gp8_low__DOT__pout));
    bufp->chgCData(oldp+172,(vlSelfRef.cla__DOT__gp8_low__DOT__cout),7);
    bufp->chgBit(oldp+173,(vlSelfRef.cla__DOT__gp8_low__DOT__g_lower));
    bufp->chgBit(oldp+174,(vlSelfRef.cla__DOT__gp8_low__DOT__p_lower));
    bufp->chgBit(oldp+175,(vlSelfRef.cla__DOT__gp8_low__DOT__g_upper));
    bufp->chgBit(oldp+176,(vlSelfRef.cla__DOT__gp8_low__DOT__p_upper));
    bufp->chgBit(oldp+177,(vlSelfRef.cla__DOT__gp8_low__DOT__c_mid));
    bufp->chgCData(oldp+178,(vlSelfRef.cla__DOT__gp8_low__DOT__gp_segment_high__DOT__gin),4);
    bufp->chgCData(oldp+179,(vlSelfRef.cla__DOT__gp8_low__DOT__gp_segment_high__DOT__pin),4);
    bufp->chgBit(oldp+180,(vlSelfRef.cla__DOT__gp8_low__DOT__gp_segment_high__DOT__cin));
    bufp->chgBit(oldp+181,(vlSelfRef.cla__DOT__gp8_low__DOT__gp_segment_high__DOT__gout));
    bufp->chgBit(oldp+182,(vlSelfRef.cla__DOT__gp8_low__DOT__gp_segment_high__DOT__pout));
    bufp->chgCData(oldp+183,(vlSelfRef.cla__DOT__gp8_low__DOT__gp_segment_high__DOT__cout),3);
    bufp->chgCData(oldp+184,(vlSelfRef.cla__DOT__gp8_low__DOT__gp_segment_low__DOT__gin),4);
    bufp->chgCData(oldp+185,(vlSelfRef.cla__DOT__gp8_low__DOT__gp_segment_low__DOT__pin),4);
    bufp->chgBit(oldp+186,(vlSelfRef.cla__DOT__gp8_low__DOT__gp_segment_low__DOT__cin));
    bufp->chgBit(oldp+187,(vlSelfRef.cla__DOT__gp8_low__DOT__gp_segment_low__DOT__gout));
    bufp->chgBit(oldp+188,(vlSelfRef.cla__DOT__gp8_low__DOT__gp_segment_low__DOT__pout));
    bufp->chgCData(oldp+189,(vlSelfRef.cla__DOT__gp8_low__DOT__gp_segment_low__DOT__cout),3);
    bufp->chgCData(oldp+190,(vlSelfRef.cla__DOT__gp8_mid1__DOT__gin),8);
    bufp->chgCData(oldp+191,(vlSelfRef.cla__DOT__gp8_mid1__DOT__pin),8);
    bufp->chgBit(oldp+192,(vlSelfRef.cla__DOT__gp8_mid1__DOT__cin));
    bufp->chgBit(oldp+193,(vlSelfRef.cla__DOT__gp8_mid1__DOT__gout));
    bufp->chgBit(oldp+194,(vlSelfRef.cla__DOT__gp8_mid1__DOT__pout));
    bufp->chgCData(oldp+195,(vlSelfRef.cla__DOT__gp8_mid1__DOT__cout),7);
    bufp->chgBit(oldp+196,(vlSelfRef.cla__DOT__gp8_mid1__DOT__g_lower));
    bufp->chgBit(oldp+197,(vlSelfRef.cla__DOT__gp8_mid1__DOT__p_lower));
    bufp->chgBit(oldp+198,(vlSelfRef.cla__DOT__gp8_mid1__DOT__g_upper));
    bufp->chgBit(oldp+199,(vlSelfRef.cla__DOT__gp8_mid1__DOT__p_upper));
    bufp->chgBit(oldp+200,(vlSelfRef.cla__DOT__gp8_mid1__DOT__c_mid));
    bufp->chgCData(oldp+201,(vlSelfRef.cla__DOT__gp8_mid1__DOT__gp_segment_high__DOT__gin),4);
    bufp->chgCData(oldp+202,(vlSelfRef.cla__DOT__gp8_mid1__DOT__gp_segment_high__DOT__pin),4);
    bufp->chgBit(oldp+203,(vlSelfRef.cla__DOT__gp8_mid1__DOT__gp_segment_high__DOT__cin));
    bufp->chgBit(oldp+204,(vlSelfRef.cla__DOT__gp8_mid1__DOT__gp_segment_high__DOT__gout));
    bufp->chgBit(oldp+205,(vlSelfRef.cla__DOT__gp8_mid1__DOT__gp_segment_high__DOT__pout));
    bufp->chgCData(oldp+206,(vlSelfRef.cla__DOT__gp8_mid1__DOT__gp_segment_high__DOT__cout),3);
    bufp->chgCData(oldp+207,(vlSelfRef.cla__DOT__gp8_mid1__DOT__gp_segment_low__DOT__gin),4);
    bufp->chgCData(oldp+208,(vlSelfRef.cla__DOT__gp8_mid1__DOT__gp_segment_low__DOT__pin),4);
    bufp->chgBit(oldp+209,(vlSelfRef.cla__DOT__gp8_mid1__DOT__gp_segment_low__DOT__cin));
    bufp->chgBit(oldp+210,(vlSelfRef.cla__DOT__gp8_mid1__DOT__gp_segment_low__DOT__gout));
    bufp->chgBit(oldp+211,(vlSelfRef.cla__DOT__gp8_mid1__DOT__gp_segment_low__DOT__pout));
    bufp->chgCData(oldp+212,(vlSelfRef.cla__DOT__gp8_mid1__DOT__gp_segment_low__DOT__cout),3);
    bufp->chgCData(oldp+213,(vlSelfRef.cla__DOT__gp8_mid2__DOT__gin),8);
    bufp->chgCData(oldp+214,(vlSelfRef.cla__DOT__gp8_mid2__DOT__pin),8);
    bufp->chgBit(oldp+215,(vlSelfRef.cla__DOT__gp8_mid2__DOT__cin));
    bufp->chgBit(oldp+216,(vlSelfRef.cla__DOT__gp8_mid2__DOT__gout));
    bufp->chgBit(oldp+217,(vlSelfRef.cla__DOT__gp8_mid2__DOT__pout));
    bufp->chgCData(oldp+218,(vlSelfRef.cla__DOT__gp8_mid2__DOT__cout),7);
    bufp->chgBit(oldp+219,(vlSelfRef.cla__DOT__gp8_mid2__DOT__g_lower));
    bufp->chgBit(oldp+220,(vlSelfRef.cla__DOT__gp8_mid2__DOT__p_lower));
    bufp->chgBit(oldp+221,(vlSelfRef.cla__DOT__gp8_mid2__DOT__g_upper));
    bufp->chgBit(oldp+222,(vlSelfRef.cla__DOT__gp8_mid2__DOT__p_upper));
    bufp->chgBit(oldp+223,(vlSelfRef.cla__DOT__gp8_mid2__DOT__c_mid));
    bufp->chgCData(oldp+224,(vlSelfRef.cla__DOT__gp8_mid2__DOT__gp_segment_high__DOT__gin),4);
    bufp->chgCData(oldp+225,(vlSelfRef.cla__DOT__gp8_mid2__DOT__gp_segment_high__DOT__pin),4);
    bufp->chgBit(oldp+226,(vlSelfRef.cla__DOT__gp8_mid2__DOT__gp_segment_high__DOT__cin));
    bufp->chgBit(oldp+227,(vlSelfRef.cla__DOT__gp8_mid2__DOT__gp_segment_high__DOT__gout));
    bufp->chgBit(oldp+228,(vlSelfRef.cla__DOT__gp8_mid2__DOT__gp_segment_high__DOT__pout));
    bufp->chgCData(oldp+229,(vlSelfRef.cla__DOT__gp8_mid2__DOT__gp_segment_high__DOT__cout),3);
    bufp->chgCData(oldp+230,(vlSelfRef.cla__DOT__gp8_mid2__DOT__gp_segment_low__DOT__gin),4);
    bufp->chgCData(oldp+231,(vlSelfRef.cla__DOT__gp8_mid2__DOT__gp_segment_low__DOT__pin),4);
    bufp->chgBit(oldp+232,(vlSelfRef.cla__DOT__gp8_mid2__DOT__gp_segment_low__DOT__cin));
    bufp->chgBit(oldp+233,(vlSelfRef.cla__DOT__gp8_mid2__DOT__gp_segment_low__DOT__gout));
    bufp->chgBit(oldp+234,(vlSelfRef.cla__DOT__gp8_mid2__DOT__gp_segment_low__DOT__pout));
    bufp->chgCData(oldp+235,(vlSelfRef.cla__DOT__gp8_mid2__DOT__gp_segment_low__DOT__cout),3);
}

void Vtop___024root__trace_cleanup(void* voidSelf, VerilatedFst* /*unused*/) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_cleanup\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VlUnpacked<CData/*0:0*/, 1> __Vm_traceActivity;
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        __Vm_traceActivity[__Vi0] = 0;
    }
    // Body
    vlSymsp->__Vm_activity = false;
    __Vm_traceActivity[0U] = 0U;
}
